apps/urls.py
"""
路由系统
"""
from flask_restful import Api

api = Api(prefix='/api/v1')

def init_api(app):
    api.init_app(app)

"""注册API路由系统"""
from apps.apis.indexapi import IndexApi

api.add_resource(IndexApi,'/index/',endpoint='index')

apps/news/models.py
import datetime
from jieba.analyse.analyzer import ChineseAnalyzer
from apps.extend import db

IS_DELETE = [
    (0,'存在'),
    (1,'删除')
]

class Cat(db.Model):
    __tablename__='cat'
    id=db.Column(db.Integer,primary_key=True)
    name=db.Column(db.String(20),nullable=False)
    color=db.Column(db.String(20),nullable=False)

class Tag(db.Model):
    __tablename__ = "tags"
    id = db.Column(db.Integer, primary_key=True)
    t_name = db.Column(db.String(16), nullable=False)
    create_time = db.Column(db.DateTime, default=datetime.datetime.now)
    is_delete = db.Column(db.Integer, nullable=False)

class News(db.Model):
    __tablename__ = "news"
    __searchable__ = ['title', 'content']
    __analyzer__ = ChineseAnalyzer()

    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(300), nullable=False)
    content = db.Column(db.Text, nullable=False)
    tid = db.Column(db.Integer,db.ForeignKey(Tag.id), nullable=False)
    img_url = db.Column(db.String(300),nullable=True)
    created_time = db.Column(db.DateTime, default=datetime.datetime.now)
    is_delete = db.Column(db.Integer, default=0)
    img_finger=db.Column(db.String(300),nullable=True)

class NewsContentImg(db.Model):
    __tablename__ = "newscontentimgs"
    id = db.Column(db.Integer, primary_key=True)
    nid = db.Column(db.Integer,db.ForeignKey(News.id), nullable=False)
    img_url = db.Column(db.String(300),nullable=True)
    created_time = db.Column(db.DateTime, default=datetime.datetime.now)
    is_delete = db.Column(db.Integer, default=0)
    img_finger=db.Column(db.String(300),nullable=True)

class Hot(db.Model):
    __tablename__ = "hots"
    id = db.Column(db.Integer, primary_key=True)
    nid = db.Column(db.Integer,db.ForeignKey(News.id), nullable=False)
    count = db.Column(db.Integer, nullable=False)

apps/collection/views.py
import datetime
from flask import Blueprint, session, request, redirect, url_for,render_template
from sqlalchemy import and_

from apps.collection.models import Collection
from apps.extend import db
from apps.news.models import News

collection = Blueprint('collection', __name__,template_folder='templates')

'''收藏页'''


# 展示收藏
@collection.route('/show/',methods=['post','get'])
def showView():

    if request.method=='GET':
        uid=session.get('id')
        if uid:
            collection_news = Collection.query.filter( and_(Collection.uid==uid,Collection.is_delete==0)).all()
            for collection_new in collection_news:
                new=News.query.filter(News.id==collection_new.nid).first()
                collection_new.new = new
            #组织桑下文模板
            context = {
                'collection_news':collection_news
            }
            return render_template('collectview.html',**context)


# 添加到收藏
@collection.route('/add/',methods=['post','get'])
def addView():
    nid = request.args.get('nid')
    uid = request.args.get('uid')
    collectnews = Collection.query.filter_by(nid=nid,uid=uid).first()
    if collectnews:
        message = '您已经收藏了!~'
    else:
        collectnews =Collection(uid=uid, nid=nid,is_delete=0)
        message = '收藏成功!~'
    db.session.add(collectnews)
    db.session.commit()

    return redirect(url_for('news.detailView',nid=nid,uid=uid,message=message))
# 删除收藏
@collection.route('/delete/',methods=['post','get'])
def deleteView():
    nid = request.args.get('nid')
    uid = session.get('id')
    collectnews = Collection.query.filter_by(nid=nid,uid=uid).first()
    if collectnews:
        collectnews.is_delete = 1
        db.session.commit()
        message = '收藏成功!~'
    else:
        message = '您未收藏!~'

    return redirect(url_for('news.detailView',nid=nid,uid=uid,message=message))



# 收藏内容
@collection.route('/collect/',methods=['post','get'])
def collectionView():
    pass

apps/news/views.py
from flask import Blueprint, render_template, request, redirect, url_for, session
from sqlalchemy import desc

from apps.user.models import User
from apps.collection.models import Collection
from apps.extend import db
from apps.news.models import Tag, News, NewsContentImg, Hot

news = Blueprint('news',__name__,template_folder='templates')

######主页#######
@news.route('/',methods=['get'])
def indexView():
    msg = request.args.get('msg')
    news = News.query.all()
    tags = Tag.query.all()
    hots = Hot.query.order_by(desc(Hot.count)).limit(7).all()
    for hot in hots:
        hotnews= News.query.filter_by(id=hot.nid).first()
        hot.new = hotnews

    try:
        del session['img_url']
    except:
        pass

    user = User.query.filter(User.username==session.get('username')).first()
    if user:
        img_url = user.img_url
        session['img_url'] = img_url
    # 组织上下文模板
    context = {
        'hots': hots,
        'news': news,
        'tags':tags,
        'msg': msg,
        'user':user
    }
    return render_template('index.html', **context)



######详情页#######
@news.route("/detail/",methods=['post','get'])
def detailView():
    message = request.args.get('message')
    id = request.args.get('nid')
    news = News.query.filter_by(id=id).first()
    user = User.query.filter_by(username=session.get('username')).first()
    bigimgs = NewsContentImg.query.filter_by(nid=id).first()
    collectnews = Collection.query.filter_by(nid=id).first()
    hotnews = Hot.query.filter_by(nid=id).first()
    if hotnews :
        hotnews.count += 1
    else:
        hotnews = Hot(nid=id,count=1)
    db.session.add(hotnews)
    db.session.commit()
    context = {
        'news': news,
        'bigimgs':bigimgs,
        'collectnews':collectnews,
        'user':user,
        'message':message,

    }
    return render_template('detail.html', **context)

######搜索页#######
@news.route("/search",methods = ['POST'])
def search():
    if not request.form['search']:
        return redirect(url_for('.index'))
    return redirect(url_for('.search_results', query=request.form['search']))


@news.route("/search_results/<query>")
def search_results(query):
    results = News.query.whoosh_search(query).all()
    print(results)
    return render_template('search_results.html', query=query, results=results)


######分类页#######
@news.route('/classify/',methods=['post','get'])
def classifyView():
    tid = request.args.get("tid")
    page = request.args.get("page",default=1,type=int)
    news = News.query.filter_by(tid=tid).paginate(page=page,per_page=5)
    context = {
        'pagination':news,
        'news':news.items,
        'tid':tid,
    }
    return render_template('classify.html',**context)

######今日热点######
@news.route('/todayhotnews/',methods=['post','get'])
def todayHotNews():
    news = News.query.order_by(desc(News.created_time)).limit(8)
    context = {
        'news': news,
    }
    return render_template('todayhotnews.html', **context)


# 赛选 多重赛选


# 富文本编辑
@news.route('/ckupload/',methods=['post','get'])
def ckUpload():
    return 'success'

apps/user/views.py
import time
import base64

import flask_whooshalchemyplus
from flask import Blueprint, render_template, request, redirect, url_for,Flask, session,make_response
from apps.config import Config
from apps.news.models import Tag, Hot, News,NewsContentImg
from apps.user.models import *
from apps.extend import login_manager, mail,github
from flask_login import login_user, login_required
from io import BytesIO
from flask_mail import Message

from flask import jsonify

user = Blueprint('user', __name__,template_folder='templates')

'''用户中心'''


"""
Flask-Login要求程序实现一个回调函数，主要是获取存储到session中user对象
"""
@login_manager.user_loader
def load_user(id):
    """
    我们需要定义一个 LoginManager.user_loader 回调函数，
    它的作用是在用户登录并调用 login_user() 的时候, 根据 user_id 找到对应的 user, 如果没有找到，返回None,
    此时的 user_id 将会自动从 session 中移除, 若能找到 user ，则 user_id 会被继续保存
    :param id:
    :return:
    """
    return db.session.query(User).get(id)

# 登录
@user.route("/login",methods=['post','get'])
def loginView():
    if request.method=='POST':
        username=request.form.get('username')
        password = request.form.get('password')
        ver_code=request.form.get('code_text').upper()
        print(ver_code)
        ver_img=session.get('img')
        print(ver_img)
        if ver_img==ver_code:
            user = User.query.filter(User.username == username).first()
            if user:
                if user.vertify_password(password):
                    login_user(user)
                    session['username']=user.username
                    session['id']=user.id
                    session['img_url'] = user.img_url
                    return redirect(url_for('news.indexView'))
                else:
                    massage = '用户名或密码错误,请重新输入'
                    return redirect(url_for('news.indexView', msg=massage))
            else:
                massage='用户名或密码错误,请重新输入'
                return redirect(url_for('news.indexView',msg=massage))
        else:
            massage='验证码错误.请重新输入'
            return redirect(url_for('news.indexView',msg=massage))

@user.route('/ajax/',methods=['post'])
def ajaxHandle():
    username=request.values.get('name')
    user=User.query.filter(username==User.username).all()
    if user:
        return 'success'
    else:
        return ''

# 注册
@user.route('/register/',methods=['post','get'])
def registerView():

    # get方式返回注册页面
    if request.method == 'GET':
        return render_template('register.html')

    # post方式完成注册功能,并返回到首页
    elif request.method=='POST':

        # 获取数据
        username=request.form.get('username')
        password=request.form.get('password')
        email=request.form.get('email')
        phone=request.form.get('phone')
        user = User.query.filter(User.username == username).all()

        # 该用户未被注册,将信息保存,完成注册
        if not user:
            try:
                user = User()
                user.username = username
                user.email = email
                user.phone = phone
                # 将密码加密并保存
                user.passwordHandle=password
                db.session.add(user)
                db.session.commit()
            # 有错误,回滚
            except:
                db.session.rollback()
                return render_template('404.html')
        else:
            return render_template('register.html', msg='该用户名已被注册')
        # 注册成功,返回首页
        return redirect(url_for('news.indexView'))
    else:
        return render_template('404.html')



# 登出
@user.route('/logout/',methods=['post','get'])
def logoutView():
    del session['username']
    del session['id']
    return redirect(url_for('news.indexView'))

# 用户激活
@user.route('/activate/',methods=['post','get'])
def activateView():
    pass


#  发送邮件:密码修改前的验证
@user.route('/emailSend/',methods=['post','get'])
def emailSendView():

    # 先获取用户邮箱信息,用于验证
    if request.method=='GET':
        return render_template('/user_info_change/email_check.html')

    # 给用户发送邮件,完成验证
    elif request.method=='POST':
        email=request.form.get('email')
        user=User.query.filter(User.email==email).first()
        # 如果邮箱正确,发送邮件
        if user:
            try:
                msg = Message(subject="邮箱验证",
                              sender=Config.MAIL_USERNAME,
                              recipients=["13781041970@163.com"])

                context = {
                    'name': user.username,
                    'id': user.id
                }
                msg.html = render_template('/user_info_change/send_for_email_check.html', **context)
                mail.send(msg)
                return redirect(url_for('news.indexView'))
            except Exception as e:
                return redirect(url_for('test.View404'))
        else:
            return render_template('/user_info_change/email_check.html',msg='该邮箱未被注册')


@user.route('/passwordChange/',methods=['post','get'])
def passwordChangeView():
    if request.method=='GET':
        id=request.args.get('id')
        user=User.query.filter(User.id==id).first()
        return render_template('/user_info_change/passwordChange.html',username=user.username,id=id)
    elif request.method=='POST':
        id=request.form.get('id')
        password=request.form.get('password')
        user=User.query.filter(User.id==id).first()
        user.passwordHandle=password
        db.session.commit()
        login_user(user)
        session['username'] = user.username
        session['id'] = user.id
        return redirect(url_for('news.indexView'))
    else:
        return '404 错误的请求方式'

@user.route('/code')
def code():
    from apps.test_app.Verification_code import create_validate_code
    code_img, strs = create_validate_code()
    buf = BytesIO()
    code_img.save(buf, 'jpeg')
    buf_str = buf.getvalue()
    response = make_response(buf_str)
    response.headers['Content-Type'] = 'image/jpeg'
    session['img'] = strs.upper()
    return response


# 管理后台用户登录
@user.route('/authlogin/',methods=['post'])
def authUserLogin():
    authname = request.form.get('authname')
    authpwd = request.form.get('authpwd')
    user = User.query.filter(User.username == 'zenglong').first()
    if authname == 'zenglong':
        if user.vertify_password(authpwd):
            login_user(user)
            session['authname'] = authname
            return redirect(url_for('admin.index'))
        else:
            context = {
                'msg' : '用户名或密码错误'
            }
            return render_template('admin/authlogin.html',**context)
    else:
        context = {
            'msg': '没有此用户'
        }
        return render_template('admin/authlogin.html',**context)

# 头像上传
@user.route('/showupload/')
def uploadShowView():
    return render_template('upload.html')

@user.route('/upload/')
def uploadView():
    image_str = request.args.get('data').split(',')[1]
    username = session.get('username')
    path = './apps/static/upload/img/' + username + '.png'
    with open(path, "wb") as file:
        file.write(base64.b64decode(image_str))

    user_img_url = '/static/upload/img/' + username + '.png'
    user = User.query.filter(User.username==username).first()
    user.img_url = user_img_url
    db.session.commit()

    # 如果用户更换头像,先清除session中的img_url
    if session.get('img_url',None):
        del session['img_url']

    return 'success'


# 用户中心
@user.route('/user_info/',methods=['post','get'])
def userInfoView():
    id=session.get('id')
    user=User.query.filter(User.id==id).first()
    tags = Tag.query.all()
    context={
        'user':user,
        'tags':tags
    }
    return render_template('user_info.html',**context)

apps/news/templates/classify.html
{% extends 'base.html' %}


{#内容模块#}
{% block content %}
    <div class="text-center col-md-offset-1" style="width: 100%">
        {% for new in news %}
             <div style="margin-bottom: 20px" class="clearfix">
                    <img src="{{ new.img_url }}" class="pull-left" style="height: 200px;width: 300px">
                    <div class="pull-left" style="margin-left: 50px ;margin-top: 75px;font-size: 20px"><a style="text-decoration: none" href="{{ url_for('news.detailView')}}?nid={{ new.id }} " >{{ new.title }}</a></div>
             </div>
        {% endfor %}

        {#分页按钮组#}
         <ul class="pagination " >
            {% if pagination.has_prev %}
                <li class="page-item active"><a class="page-link" href="{{ url_for('news.classifyView')}}?tid={{ tid }}&page={{ pagination.page - 1 }}">上一页</a></li>
            {% else %}
                <li class="page-item disabled"><a class="page-link" href="#">上一页</a></li>
            {% endif %}

            {% for page in pagination.iter_pages(4) %}
                {% if page %}
                    <li class="page-item {% if page==pagination.page %}active{% endif %}"><a class="page-link" href="{{ url_for('news.classifyView')}}?tid={{ tid }}&page={{ page }}">{{ page }}</a></li>
                {% else %}
                    <li class="page-item disabled"><a class="page-link" href="#">&hellip;</a></li>
                {% endif %}

            {% endfor %}

            {% if pagination.has_next %}
                <li class="page-item"><a class="page-link" href="{{ url_for('news.classifyView')}}?tid={{ tid }}&page={{ pagination.page + 1 }}">下一页</a>
                </li>
            {% else %}
                <li class="page-item disabled"><a class="page-link" href="#">下一页</a></li>
            {% endif %}
         </ul>
    </div>
{% endblock %}

apps/news/templates/detail.html
{% extends 'base.html' %}


{#内容模块#}
{% block content %}
<div class="container">
   <div class="row">
      <div class="col-md-2">
          <a class="collect" href="{{ url_for('collection.addView') }}?nid={{ news.id }}&uid={{ user.id }}"><img src="{{ url_for('static',filename='logo/zhuanfa.png')}}"></a>
          <form role="form" style="width: 100px;padding: 0;" action="{{ url_for('news.detailView') }}?nid={{ news.id }}&uid={{ user.id }}" method="POST">
           {% if message %}
               <h5 style="margin-top: 10px;color: red">{{ message }}</h5>
           {% endif %}
          </form>
      </div>
      <div class="col-md-8">
          <h2 style="left: 50px">{{ news.title }}</h2>
          <a><img src="{{ bigimgs.img_url }}"style="width: 100%"></a>
          <h4 style="font-family: 华文楷体;letter-spacing: 2px;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{ news.content }}</h4>
      </div>

{#        富文本编辑#}
      <div class="col-md-2">
          <div style="margin-top: 60px" class="text-center">
              <form method="post" action="{{ url_for('news.ckUpload') }}" enctype="multipart/form-data" >
                <textarea name="content" id="content" placeholder="内容" cols="60" ></textarea>
                <input type="submit" class="btn btn-primary text-center" value="立即发布">

{#                替换textarea#}
                <script type="text/javascript">
                    CKEDITOR.replace('content', {
                {#开启上传功能，配置上传路径#}
                        language: 'zh-cn',
                        filebrowserUploadUrl: '/ckupload/',
                        toolbar: [['Bold', 'Italic', '-', 'NumberedList', 'BulletedList','-'],['Image']]
                    });
                </script>
              </form>
          </div>
      </div>

   </div>
</div>

{% endblock %}

apps/news/templates/index.html
{% extends 'index_base.html' %}
{% block css %}
<style>
/* Custom Styles */
    ul.nav-tabs {
        width: 150px;
        height: 100%;
    }
</style>
{% endblock %}


 {% block catagory %}
     <div style="width: 100%;background-color: #2b669a;">
        <div class="col-xs-3" id="myScrollspy">
            <div>
                <ul class="nav nav-tabs nav-stacked"  data-offset-top="125">
                    <li><img src="{{ url_for('static',filename='logo/logo3.jpg') }}" style="width:150px; height:100px"></li>
                    {% for tag in tags %}
                        <li class="bg-info" ><a href="{{ url_for('news.classifyView')}}?tid={{ tag.id }}" style="height:70px;font-size: 29px" class="text-center">{{ tag.t_name }}</a></li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
 {% endblock %}

{% block banner %}
    <div style="width: 100%;height:300px;background-color: #5bc0de;" >

        <div id="slidershow" class="carousel slide" data-ride="carousel"
             style="position: relative;clear: both">
            <!-- 设置图片轮播的顺序 -->
            <ol class="carousel-indicators">
                <li class="active" data-target="#slidershow" data-slide-to="0">
                <li data-target="#slidershow" data-slide-to="1">
                <li data-target="#slidershow" data-slide-to="2">
            </ol>
            <!-- 设置轮播图片 -->
            <div class="carousel-inner">
                <div class="item active">
                    <a href="#"><img src="{{ url_for('static',filename='banner/1.jpg') }}"
                                     style="height: 100%;width: 100%"></a>
                    <div class="carousel-caption" style="font-size: large">习近平同巴布亚新几内亚总理奥尼尔会谈</div>
                </div>
                <div class="item">
                    <a href="#"><img src="{{ url_for('static',filename='banner/2.jpg') }}"
                                     style="height: 100%;width: 100%"></a>
                    <div class="carousel-caption" style="font-size: large">青海西宁降下大雪 道路结冰影响市民出行</div>
                </div>
                <div class="item">
                    <a href="#"><img src="{{ url_for('static',filename='banner/3.jpg') }}"
                                     style="height: 100%;width: 100%"></a>
                    <div class="carousel-caption" style="font-size: large">5岁男孩一次做4105个俯卧撑 获赠奔驰车</div>
                </div>
            </div>
            <!-- 设置轮播图片控制器 -->
            <a class="left carousel-control" href="#slidershow" role="button" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left"></span>
            </a>
            <a class="right carousel-control" href="#slidershow" role="button" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right"></span>
            </a>
        </div>


    </div>
{% endblock %}


{% block newslist %}
    <div style="width: 100%;height:1000px;">
        <table class="table">
            {% for new in news %}
                <tr>
                    <th  class="col-md-3 list-group-item" ><a href="{{ url_for('news.detailView') }}?nid={{ new.id }}"><img src="{{ new.img_url }}" style="height: 100px;width: 158px;"></a></th>
                    <th  class="col-md-9 list-group-item" ><a style="text-decoration:none;color:black " href="{{ url_for('news.detailView') }}?nid={{ new.id }}"><h3 >{{ new.title }}</h3></a></th>
                </tr>
            {% endfor %}
        </table>
    </div>

{% endblock %}


{% block user %}
    <div style="width:100%;height: auto;">
        <div style="width:100%">
            <div style="width:100%;height: auto;border: lightgray solid 1px;border-radius:4px;">
                <form class="navbar-form navbar-left" style="width: inherit;padding: 0;" action="{{url_for('news.search')}}" method="POST">
                    <div class="form-group" style="display: inline-block;width: 69%;margin-left: 10px">
                        <input type="text" class="form-control" placeholder="搜索" style="width:100%" name="search">
                    </div>
                    <button type="submit" class="btn btn-default" style="margin-right: 10px;margin-left:3px;width: 20%"><span class="glyphicon glyphicon-search"></span></button>
                </form>
                <br>
                <br>
                <br>
                {% if  session.username %}
                    <div>
                        <h4 style="margin-left: 20px">亲爱的:<a>{{ session.username }}</a></h4>

                {% else %}
                    <div style="margin-top:-9px;border-top: lightgray solid 1px;">
                    <div style="width: inherit;height: 30px;text-align: center;">
                        <h4><strong>账号密码登陆</strong></h4>
                    </div>

                    <form class="form-horizontal" role="form" style="width: inherit;padding: 0;" action="{{ url_for('user.loginView') }}" method="POST">
                        <div class="form-group" style="width: 100%;margin: 0">
                            <label for="firstname" class="col-sm-4 control-label" style="width:32%;margin: 0;">用户名:</label>
                            <input type="text" style="width: 64%;" class="form-control" id="firstname" placeholder="请输入用户名" name="username">
                        </div>
                        <div class="form-group" style="width: 100%;margin: 0;margin-top: 7px">
                            <label for="lastname" class="col-sm-4 control-label" style="width:32%;display: inline-block">密码:</label>
                            <input type="password" style="width: 64%" class=" form-control" id="lastname" placeholder="请输入密码" name="password">
                        </div>
                        <div  class="form-group" style="width: 100%;margin: 0;margin-top: 7px">
                            <label  class="col-sm-4 control-label" style="width:32%;display: inline-block">验证码</label>
                            <input type="text" style="width: 64%" class="form-control" id="code1" placeholder="请输入验证码" name="code_text">
                            <img id="code" src="{{ url_for('user.code') }}" onclick="ajax1()" style="margin-left: 90px;margin-top: 10px">
                            <p style="margin-left: 50px;margin-top: 10px;">点击图片即可刷新验证码</p>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <div class="checkbox">
                                    <label>
                                        <input type="checkbox">请记住我
                                        <a href="{{ url_for('user.emailSendView')}}" style="text-decoration: none;margin-left: 7px"><span>忘记密码?</span></a>
                                    </label>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-info">登录</button>
                                <a href="{{ url_for('user.registerView') }}" style="margin-left: 5px">
                                    <button type="button" class="btn btn-default">注册</button>
                                </a>
                               <div>
                                   {% if msg %}
                                       <h5 style="margin-top: 10px;color: red">{{ msg }}</h5>
                                   {% endif %}
                               </div>
                            </div>
                        </div>

                    </form>
                </div>
                {% endif %}
                </div>
            </div>
        </div>
    </div>
<script>
    function ajax1() {
        var xhr = new XMLHttpRequest();
        xhr.open('GET', "{{ url_for('user.code') }}",true);
        xhr.onreadystatechange = function () {
            if (xhr.readyState == 4){
                $('#code').attr('src',"{{ url_for('user.code') }}?"+Math.random())
            }
        };
        xhr.send()
    }
</script>
{% endblock %}

{% block hot %}
    <div style="width:100%;height: auto;">
        <div class="pane-module hot-words-pane">
            <a class="list-group-item active">
                <h4 style="font-weight:bold">热搜新闻</h4>
            </a>
            {% for hot in  hots %}
                  <a class='list-group-item' href="{{ url_for('news.detailView')}}?nid={{ hot.nid }}">{{ hot.new.title }}</a>
            {% endfor %}
{#                <img src="//s3.pstatp.com/toutiao/static/img/icon_hot_search_t2.4c778ee.png" alt style="float: right"#}
{#                     height="20px">#}
        </div>
        <div class="pane-module hot-words-pane">
            <a class="list-group-item active">
                <h4 style="font-weight:bold">猜你喜欢</h4></a>
            <a href="https://www.toutiao.com/group/6624658828648513795/" class="list-group-item">
                <div class="media">
                    <div class="media-left">
                        <img src="//p99.pstatp.com/list/240x240/da930002dd377261adf6" class="media-object"
                             style="width:60px"></div>
                    <div class="media-body" style="padding: 10px">
                        选三缸福克斯还是四缸高尔夫？广州车展找答案
                    </div>
                </div>
            </a>
            <a href="https://www.toutiao.com/group/6618359724360335620/" class="list-group-item">
                <div class="media">
                    <div class="media-left">
                        <img src="https://p3.pstatp.com/list/240x240/dab70000a6710e337062" class="media-object"
                             style="width:60px">
                    </div>
                    <div class="media-body" style="padding: 10px">
                        2018今日头条生机大会
                    </div>
                </div>
            </a>
            <a href="https://www.toutiao.com/group/6624417815111696904/" class="list-group-item">
                <div class="media">
                    <div class="media-left">
                        <img src="https://p1.pstatp.com/list/240x240/pgc-image/a452e01cdcfe41b386cbe0c807f20e4c"
                             class="media-object"
                             style="width:60px">
                    </div>
                    <div class="media-body" style="padding: 10px">
                        易到回应高管给CEO磕头风波：遭险恶有预谋饭局 已向警方报案
                    </div>
                </div>
            </a>
            <a href="https://www.toutiao.com/group/6624687499392320007/" class="list-group-item">
                <div class="media">
                    <div class="media-left">
                        <img src="https://p1.pstatp.com/list/240x240/pgc-image/R9dA5RDFlzBJyu" class="media-object"
                             style="width:60px">
                    </div>
                    <div class="media-body" style="padding: 10px">
                        枪枪毙命：美国德州农场主用夜视仪狙击枪击毙45头郊狼
                    </div>
                </div>
            </a>
        </div>
    </div>
{% endblock %}

apps/news/templates/todayhotnews.html
{% extends 'base.html' %}

{% block content %}
    <div style="width: 80%;" class="col-md-offset-1">
        <table class="table">
            {% for new in news %}
                <tr>
                    <th  class="col-md-3 " ><a href="{{ url_for('news.detailView') }}?nid={{ new.id }}"><img src="{{ new.img_url }}" style="width: 100%;"></a></th>
                    <th  class="col-md-9 " style="vertical-align:middle;" ><a style="text-decoration:none;color:black; " href="{{ url_for('news.detailView') }}?nid={{ new.id }}"><h3 >{{ new.title }}</h3></a></th>
                </tr>
            {% endfor %}
        </table>
    </div>

{% endblock %}