apps/urls.py
"""
路由系统
"""
from flask_restful import Api

api = Api(prefix='/api/v1')

def init_api(app):
    api.init_app(app)

"""注册API路由系统"""
from apps.apis.indexapi import IndexApi

api.add_resource(IndexApi,'/index/',endpoint='index')

apps/user/models.py
import datetime
from apps.extend import db
from flask_login import UserMixin
from werkzeug.security import generate_password_hash,check_password_hash

'''
choice
'''
IS_ACTIVE = [
    (0, '未激活'),
    (1, '激活')
]
IS_DELETE = [
    (0, '存在'),
    (1, '删除')
]


class User(db.Model,UserMixin):
    __tablename__ = "user"
    id = db.Column(db.Integer, primary_key=True)
    img_url = db.Column(db.String(200))
    username = db.Column(db.String(20), nullable=False)
    password = db.Column(db.String(100), nullable=False)
    email = db.Column(db.String(100), nullable=False)
    phone = db.Column(db.String(40), nullable=False)
    is_active = db.Column(db.Boolean, default=0)
    flag = db.Column(db.String(100))
    is_delete = db.Column(db.Boolean, default=0)
    create_time = db.Column(db.DateTime, default=datetime.datetime.now)

    # 当主键不为id时必须重写该方法
    # def get_id(self):
    #     return self.uid

    # 获取私有属性 password = user.password
    @property
    def passwordHandle(self):
        return self.password

    # 设置私有属性 user.password = "1111111"
    @passwordHandle.setter
    def passwordHandle(self, password):
        # if re.findall('^[A-Z]{1}(\w){5,11}',password):
        if password:
            self.password = generate_password_hash(password=password)
        else:
            raise Exception('密码不符合规范')

    """
    删除私有属性 del user.password
    @password.deleter
    def password(self):
        del self._password_hash
    """

    def vertify_password(self, password):
        return check_password_hash(self.password, password=password)

class AuthUser(db.Model,UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    first_name = db.Column(db.String(255))
    last_name = db.Column(db.String(255))
    email = db.Column(db.String(255), unique=True)
    password = db.Column(db.String(255))
    active = db.Column(db.Boolean())
    confirmed_at = db.Column(db.DateTime())

    def __str__(self):
        return self.email

apps/collection/views.py
import datetime
from flask import Blueprint, session, request, redirect, url_for,render_template
from sqlalchemy import and_

from apps.collection.models import Collection
from apps.extend import db
from apps.news.models import News

collection = Blueprint('collection', __name__,template_folder='templates')

'''收藏页'''


# 展示收藏
@collection.route('/show/',methods=['post','get'])
def showView():

    if request.method=='GET':
        uid=session.get('id')
        if uid:
            collection_news = Collection.query.filter( and_(Collection.uid==uid,Collection.is_delete==0)).all()
            for collection_new in collection_news:
                new=News.query.filter(News.id==collection_new.nid).first()
                collection_new.new = new
            #组织桑下文模板
            context = {
                'collection_news':collection_news
            }
            return render_template('collectview.html',**context)


# 添加到收藏
@collection.route('/add/',methods=['post','get'])
def addView():
    nid = request.args.get('nid')
    uid = request.args.get('uid')
    collectnews = Collection.query.filter_by(nid=nid,uid=uid).first()
    if collectnews:
        message = '您已经收藏了!~'
    else:
        collectnews =Collection(uid=uid, nid=nid,is_delete=0)
        message = '收藏成功!~'
    db.session.add(collectnews)
    db.session.commit()

    return redirect(url_for('news.detailView',nid=nid,uid=uid,message=message))
# 删除收藏
@collection.route('/delete/',methods=['post','get'])
def deleteView():
    nid = request.args.get('nid')
    uid = session.get('id')
    collectnews = Collection.query.filter_by(nid=nid,uid=uid).first()
    if collectnews:
        collectnews.is_delete = 1
        db.session.commit()
        message = '收藏成功!~'
    else:
        message = '您未收藏!~'

    return redirect(url_for('news.detailView',nid=nid,uid=uid,message=message))



# 收藏内容
@collection.route('/collect/',methods=['post','get'])
def collectionView():
    pass

apps/news/views.py
from flask import Blueprint, render_template, request, redirect, url_for, session
from sqlalchemy import desc

from apps.user.models import User
from apps.collection.models import Collection
from apps.extend import db
from apps.news.models import Tag, News, NewsContentImg, Hot

news = Blueprint('news',__name__,template_folder='templates')

######主页#######
@news.route('/',methods=['get'])
def indexView():
    msg = request.args.get('msg')
    news = News.query.all()
    tags = Tag.query.all()
    hots = Hot.query.order_by(desc(Hot.count)).limit(7).all()
    for hot in hots:
        hotnews= News.query.filter_by(id=hot.nid).first()
        hot.new = hotnews

    try:
        del session['img_url']
    except:
        pass

    user = User.query.filter(User.username==session.get('username')).first()
    if user:
        img_url = user.img_url
        session['img_url'] = img_url
    # 组织上下文模板
    context = {
        'hots': hots,
        'news': news,
        'tags':tags,
        'msg': msg,
        'user':user
    }
    return render_template('index.html', **context)



######详情页#######
@news.route("/detail/",methods=['post','get'])
def detailView():
    message = request.args.get('message')
    id = request.args.get('nid')
    news = News.query.filter_by(id=id).first()
    user = User.query.filter_by(username=session.get('username')).first()
    bigimgs = NewsContentImg.query.filter_by(nid=id).first()
    collectnews = Collection.query.filter_by(nid=id).first()
    hotnews = Hot.query.filter_by(nid=id).first()
    if hotnews :
        hotnews.count += 1
    else:
        hotnews = Hot(nid=id,count=1)
    db.session.add(hotnews)
    db.session.commit()
    context = {
        'news': news,
        'bigimgs':bigimgs,
        'collectnews':collectnews,
        'user':user,
        'message':message,

    }
    return render_template('detail.html', **context)

######搜索页#######
@news.route("/search",methods = ['POST'])
def search():
    if not request.form['search']:
        return redirect(url_for('.index'))
    return redirect(url_for('.search_results', query=request.form['search']))


@news.route("/search_results/<query>")
def search_results(query):
    results = News.query.whoosh_search(query).all()
    print(results)
    return render_template('search_results.html', query=query, results=results)


######分类页#######
@news.route('/classify/',methods=['post','get'])
def classifyView():
    tid = request.args.get("tid")
    page = request.args.get("page",default=1,type=int)
    news = News.query.filter_by(tid=tid).paginate(page=page,per_page=5)
    context = {
        'pagination':news,
        'news':news.items,
        'tid':tid,
    }
    return render_template('classify.html',**context)

######今日热点######
@news.route('/todayhotnews/',methods=['post','get'])
def todayHotNews():
    news = News.query.order_by(desc(News.created_time)).limit(8)
    context = {
        'news': news,
    }
    return render_template('todayhotnews.html', **context)


# 赛选 多重赛选


# 富文本编辑
@news.route('/ckupload/',methods=['post','get'])
def ckUpload():
    return 'success'

apps/user/views.py
import time
import base64

import flask_whooshalchemyplus
from flask import Blueprint, render_template, request, redirect, url_for,Flask, session,make_response
from apps.config import Config
from apps.news.models import Tag, Hot, News,NewsContentImg
from apps.user.models import *
from apps.extend import login_manager, mail,github
from flask_login import login_user, login_required
from io import BytesIO
from flask_mail import Message

from flask import jsonify

user = Blueprint('user', __name__,template_folder='templates')

'''用户中心'''


"""
Flask-Login要求程序实现一个回调函数，主要是获取存储到session中user对象
"""
@login_manager.user_loader
def load_user(id):
    """
    我们需要定义一个 LoginManager.user_loader 回调函数，
    它的作用是在用户登录并调用 login_user() 的时候, 根据 user_id 找到对应的 user, 如果没有找到，返回None,
    此时的 user_id 将会自动从 session 中移除, 若能找到 user ，则 user_id 会被继续保存
    :param id:
    :return:
    """
    return db.session.query(User).get(id)

# 登录
@user.route("/login",methods=['post','get'])
def loginView():
    if request.method=='POST':
        username=request.form.get('username')
        password = request.form.get('password')
        ver_code=request.form.get('code_text').upper()
        print(ver_code)
        ver_img=session.get('img')
        print(ver_img)
        if ver_img==ver_code:
            user = User.query.filter(User.username == username).first()
            if user:
                if user.vertify_password(password):
                    login_user(user)
                    session['username']=user.username
                    session['id']=user.id
                    session['img_url'] = user.img_url
                    return redirect(url_for('news.indexView'))
                else:
                    massage = '用户名或密码错误,请重新输入'
                    return redirect(url_for('news.indexView', msg=massage))
            else:
                massage='用户名或密码错误,请重新输入'
                return redirect(url_for('news.indexView',msg=massage))
        else:
            massage='验证码错误.请重新输入'
            return redirect(url_for('news.indexView',msg=massage))

@user.route('/ajax/',methods=['post'])
def ajaxHandle():
    username=request.values.get('name')
    user=User.query.filter(username==User.username).all()
    if user:
        return 'success'
    else:
        return ''

# 注册
@user.route('/register/',methods=['post','get'])
def registerView():

    # get方式返回注册页面
    if request.method == 'GET':
        return render_template('register.html')

    # post方式完成注册功能,并返回到首页
    elif request.method=='POST':

        # 获取数据
        username=request.form.get('username')
        password=request.form.get('password')
        email=request.form.get('email')
        phone=request.form.get('phone')
        user = User.query.filter(User.username == username).all()

        # 该用户未被注册,将信息保存,完成注册
        if not user:
            try:
                user = User()
                user.username = username
                user.email = email
                user.phone = phone
                # 将密码加密并保存
                user.passwordHandle=password
                db.session.add(user)
                db.session.commit()
            # 有错误,回滚
            except:
                db.session.rollback()
                return render_template('404.html')
        else:
            return render_template('register.html', msg='该用户名已被注册')
        # 注册成功,返回首页
        return redirect(url_for('news.indexView'))
    else:
        return render_template('404.html')



# 登出
@user.route('/logout/',methods=['post','get'])
def logoutView():
    del session['username']
    del session['id']
    return redirect(url_for('news.indexView'))

# 用户激活
@user.route('/activate/',methods=['post','get'])
def activateView():
    pass


#  发送邮件:密码修改前的验证
@user.route('/emailSend/',methods=['post','get'])
def emailSendView():

    # 先获取用户邮箱信息,用于验证
    if request.method=='GET':
        return render_template('/user_info_change/email_check.html')

    # 给用户发送邮件,完成验证
    elif request.method=='POST':
        email=request.form.get('email')
        user=User.query.filter(User.email==email).first()
        # 如果邮箱正确,发送邮件
        if user:
            try:
                msg = Message(subject="邮箱验证",
                              sender=Config.MAIL_USERNAME,
                              recipients=["13781041970@163.com"])

                context = {
                    'name': user.username,
                    'id': user.id
                }
                msg.html = render_template('/user_info_change/send_for_email_check.html', **context)
                mail.send(msg)
                return redirect(url_for('news.indexView'))
            except Exception as e:
                return redirect(url_for('test.View404'))
        else:
            return render_template('/user_info_change/email_check.html',msg='该邮箱未被注册')


@user.route('/passwordChange/',methods=['post','get'])
def passwordChangeView():
    if request.method=='GET':
        id=request.args.get('id')
        user=User.query.filter(User.id==id).first()
        return render_template('/user_info_change/passwordChange.html',username=user.username,id=id)
    elif request.method=='POST':
        id=request.form.get('id')
        password=request.form.get('password')
        user=User.query.filter(User.id==id).first()
        user.passwordHandle=password
        db.session.commit()
        login_user(user)
        session['username'] = user.username
        session['id'] = user.id
        return redirect(url_for('news.indexView'))
    else:
        return '404 错误的请求方式'

@user.route('/code')
def code():
    from apps.test_app.Verification_code import create_validate_code
    code_img, strs = create_validate_code()
    buf = BytesIO()
    code_img.save(buf, 'jpeg')
    buf_str = buf.getvalue()
    response = make_response(buf_str)
    response.headers['Content-Type'] = 'image/jpeg'
    session['img'] = strs.upper()
    return response


# 管理后台用户登录
@user.route('/authlogin/',methods=['post'])
def authUserLogin():
    authname = request.form.get('authname')
    authpwd = request.form.get('authpwd')
    user = User.query.filter(User.username == 'zenglong').first()
    if authname == 'zenglong':
        if user.vertify_password(authpwd):
            login_user(user)
            session['authname'] = authname
            return redirect(url_for('admin.index'))
        else:
            context = {
                'msg' : '用户名或密码错误'
            }
            return render_template('admin/authlogin.html',**context)
    else:
        context = {
            'msg': '没有此用户'
        }
        return render_template('admin/authlogin.html',**context)

# 头像上传
@user.route('/showupload/')
def uploadShowView():
    return render_template('upload.html')

@user.route('/upload/')
def uploadView():
    image_str = request.args.get('data').split(',')[1]
    username = session.get('username')
    path = './apps/static/upload/img/' + username + '.png'
    with open(path, "wb") as file:
        file.write(base64.b64decode(image_str))

    user_img_url = '/static/upload/img/' + username + '.png'
    user = User.query.filter(User.username==username).first()
    user.img_url = user_img_url
    db.session.commit()

    # 如果用户更换头像,先清除session中的img_url
    if session.get('img_url',None):
        del session['img_url']

    return 'success'


# 用户中心
@user.route('/user_info/',methods=['post','get'])
def userInfoView():
    id=session.get('id')
    user=User.query.filter(User.id==id).first()
    tags = Tag.query.all()
    context={
        'user':user,
        'tags':tags
    }
    return render_template('user_info.html',**context)

apps/user/templates/error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
测试
</body>
</html>

apps/user/templates/login.html
{% extends 'base.html' %}

apps/user/templates/register.html
{% extends 'base.html' %}
{% block content %}
    <div style="width: 60%;height: auto;margin-left:17%;margin-top: 20px">

        <!--欢迎语句-->
        <span style="text-align: center;"><h1>欢迎来到用户注册系统</h1></span>

        <!--用户注册-->
        <form class="form-horizontal" role="form" action="{{ url_for('user.registerView') }}" method="post">

            <!--用户名-->
            <div class="form-group">
                <label for="username" class="col-sm-2 control-label" style="font-size:large">用户名</label>
                <div class="col-sm-8">
                    <input type="text" style="width: 91%;display: inline-block" name="username" class="form-control" id="username" placeholder="请输入用户名">
                    <!--验证反馈信息-->
                    <div style="color: red;display: none" id="msg">该用户名已被注册</div>
                    <span id="usernameRight" style="color: green;font-style: italic;width: 9%;display: none">good!</span>
                    <div id="usernameError" style="color: red;display: none">用户名只能包含字母/数字/下划线,且不能以数字开头,长度在6～12位
                    </div>
                </div>
            </div>


            <!--密码-->
            <div class="form-group">
                <label for="password" class="col-sm-2 control-label" style="font-size:large">密码</label>
                <div class="col-sm-8">
                    <input type="password" style="width: 91%;display: inline-block" name="password" class="form-control" id="password" placeholder="请输入密码">
                    <!--验证反馈信息-->
                    <span id="passwordRight" style="color: green;font-style: italic;width: 9%;display: none">good!</span>
                    <div id="passwordError" style="color: red;display: none">密码只能包含字母/数字/下划线,长度在6～12位</div>
                </div>
            </div>

            <!--确认密码-->
            <div class="form-group">
                <label for="repassword" class="col-sm-2 control-label" style="font-size:large">确认密码</label>
                <div class="col-sm-8">
                    <input type="password" style="width: 91%;display: inline-block" name="repassword" class="form-control" id="repassword" placeholder="请再次输入密码">
                    <!--验证反馈信息-->
                    <span id="repasswordRight" style="color: green;font-style: italic;width: 9%;display: none">good!</span>
                    <div id="repasswordError" style="color: red;display: none">两次输入的密码不一致</div>
                </div>
            </div>

            <!--email-->
            <div class="form-group">
                <label for="email" class="col-sm-2 control-label" style="font-size:large">邮箱</label>
                <div class="col-sm-8">
                    <input type="text" style="width: 91%;display: inline-block" name="email" class="form-control" id="email" placeholder="邮箱">
                    <!--验证反馈信息-->
                    <span id="emailRight" style="color: green;font-style: italic;width: 9%;display: none">good!</span>
                    <div id="emailError" style="color: red;display: none">错误的邮箱格式</div>
                </div>
            </div>

            <!--phone-->
            <div class="form-group">
                <label for="phone" class="col-sm-2 control-label" style="font-size:large">电话</label>
                <div class="col-sm-8">
                    <input type="text" style="width: 91%;display: inline-block" name="phone" class="form-control" id="phone" placeholder="电话">
                    <!--验证反馈信息-->
                    <span id="phoneRight" style="color: green;font-style: italic;width: 9%;display: none">good!</span>
                    <div id="phoneError" style="color: red;display: none">无效的号码</div>
                </div>
            </div>

            <!--请记住我-->
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <div class="checkbox">
                        <label>
                            <input type="checkbox">请记住我
                        </label>
                    </div>
                </div>
            </div>

            <!--注册提交-->
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" id="register" disabled class="btn btn-info">注册</button>
                </div>
            </div>

        </form>
    </div>
{% endblock %}


{% block js %}

    <script type="text/javascript">

        $(function () {
            //检查用户名可用性(是否已被注册)
            $('#username').blur(function () {
                $('#msg').hide();
                //定义睡眠函数
                var t = Date.now();
                function sleep(d) {
                    while (Date.now - t <= d) ;
                };
                sleep(2000);
                var name = $("#username").val();
                var data = {"name": name};
                $.post('/user/ajax/', data, function (data) {
                    if (data) {
                        $('#msg').show();
                        $('#usernameError').hide();
                        $('#usernameRight').hide();
                    }
                });
            });

            //(动态输入时检查)用户名验证
            $("#username").on('input', function () {
                $('#msg').hide();
                var regtitle = /^[a-zA-Z][a-zA-Z0-9_]{5,11}$/;
                var uname = $("#username").val();
                if (uname.length <= 0 || !regtitle.test(uname)) {
                    $("#usernameRight").hide();
                    $("#usernameError").show();
                } else {
                    $("#usernameRight").show();
                    $("#usernameError").hide();
                }
            });

            //(动态输入时检查)密码验证
            $("#password").on('input', function () {
                var regtitle = /^[a-zA-Z0-9_]{6,12}$/;
                var uname = $("#password").val();
                if (uname.length <= 0 || !regtitle.test(uname)) {
                    $("#passwordRight").hide();
                    $("#passwordError").show();
                } else {
                    $("#passwordRight").show();
                    $("#passwordError").hide();
                }

                //(用户调用历史记录时)检查用户名合法性
                var regtitle1 = /^[a-zA-Z][a-zA-Z0-9_]{5,11}$/;
                var uname1 = $("#username").val();
                if (uname1.length <= 0 || !regtitle1.test(uname1)) {
                    $("#usernameRight").hide();
                } else {
                    $("#usernameRight").show();
                    $("#usernameError").hide();
                }

                //(用户调用历史记录时)邮箱合法性
                var regemail1 = /^[a-zA-Z0-9_-]+@[a-zA-Z0-9_-]+(\.[a-zA-Z0-9_-]+)+$/;
                var uemail1 = $("#email").val();
                if (uemail1.length <= 0 || !regemail1.test(uemail1)) {
                    $("#emailRight").hide();
                } else {
                    $("#emailRight").show();
                    $("#emailError").hide();
                }

                //(用户调用历史记录时)电话合法性
                var regphone1 = /^1[34578]\d{9}$/;
                var uphone1 = $("#phone").val();
                if (uphone1.length <= 0 || !regphone1.test(uphone1)) {
                    $("#phoneRight").hide();
                } else {
                    $("#phoneRight").show();
                    $("#phoneError").hide();
                }
            });

            //(动态输入时检查)确认密码
            $("#repassword").on('input', function () {
                var pwd = $("#password").val();
                var repwd = $("#repassword").val();
                if (pwd !== repwd || repwd.length <= 0) {
                    $("#repasswordRight").hide();
                    $("#repasswordError").show();
                } else {
                    $("#repasswordRight").show();
                    $("#repasswordError").hide();
                }
            });

            //(动态输入时检查)邮箱验证
            $("#email").on('input', function () {
                var regemail = /^[a-zA-Z0-9_-]+@[a-zA-Z0-9_-]+(\.[a-zA-Z0-9_-]+)+$/;
                var uemail = $("#email").val();
                if (uemail.length <= 0 || !regemail.test(uemail)) {
                    $("#emailRight").hide();
                    $("#emailError").show();
                } else {
                    $("#emailRight").show();
                    $("#emailError").hide();
                }
            });

            //(动态输入时检查)电话号码验证
            $("#phone").on('input', function () {
                var regphone = /^1[34578]\d{9}$/;
                var uphone = $("#phone").val();
                if (uphone.length <= 0 || !regphone.test(uphone)) {
                    $("#phoneRight").hide();
                    $("#phoneError").show();
                } else {
                    $("#phoneRight").show();
                    $("#phoneError").hide();
                }
            });

            //以上全部通过,允许注册
            $('input').on('input', function () {
                if ($('#usernameRight').is(':visible') && $('#passwordRight').is(':visible') &&
                    $('#repasswordRight').is(':visible') && $('#emailRight').is(':visible') &&
                    $('#phoneRight').is(':visible')) {
                    $('#register').removeAttr("disabled");
                }
            });

        })

    </script>
{% endblock %}

apps/user/templates/user_info.html
{% extends 'base.html' %}
{% block css %}
    <link rel="stylesheet" href="http://uc-vs.bdimg.com/v4/20181107x2/asset/home/css/main.css">
    <style type="text/css">
        body {
            background: whitesmoke;
        }

        #img img {
            height: 200px;
            width: 250px;
            margin-top: 1%;
            margin-left: 10px;
        }

        #img div {
            width: 250px;
            margin-top: 2%;
            margin-left: 10px;
            text-align: center;
        }

        #chao a {
            text-decoration: none;
            color: black;
            margin-left: 20px;
            position: relative;
            top: 15px;
        }
    </style>
{% endblock %}


{% block js %}
    <script type="text/javascript">
        $('#myTabs a').click(function (e) {
            e.preventDefault();
            $(this).tab('show')
        });

        function info() {
            $('#alt').show();
        }

        function drop() {
            $('#alt').hide();
        }

    </script>
{% endblock %}
{% block content %}

    <div style="" class="col-md-offset-1">
    <!--超链接区-->
    <div style="width: 90%;height:40px;border: lightgrey solid 1px;background: white">
         {% for tag in tags %}
            <a style="text-decoration: none" href="{{ url_for('news.classifyView') }}?tid={{ tag.id }}">{{ tag.t_name }}
                &nbsp&nbsp&nbsp <span style="color: lightgrey">|&nbsp&nbsp&nbsp</span></a>
        {% endfor %}
    </div>

    <!--用户区-->
    <div style="background: white;width: 20%;height: 280px;border: lightgrey solid 1px;margin-top: 10px;display: inline-block">

    <!--用户头像-->
    <div style="width: 70%;height:70%;margin-left: 15%;text-align: center">
        <a href="{{ url_for('user.uploadShowView') }}">
            <div onmouseover="info()" onmouseleave="drop()"
                 style="width: 75%;height: 65%;margin-left: 12.5%;margin-top: 15%">
                <img class="img-thumbnail" src="{{ user.img_url }}">
                <div id="alt"
                     style="background: #5e5e5e; opacity: 0.7;position: relative;top: -24px;height:25px;width:100%;display: none;color: white">
                    更改图片
                </div>
            </div>
        </a>
        <div style="text-align: center;margin-top: 5%">
            <h4>{{ user.username }}</h4>
        </div>
    </div>

    <!--密码修改及订阅中心-->
    <div style="width: 90%;border-top:dodgerblue solid 1px;margin-left: 5%;margin-top:-5%;height: 25%;text-align: center;color: black">
        <div style="margin-top: 10%">
            <a href="{{ url_for('user.uploadShowView') }}">
                <div style="width: 50%;border-right: lightgrey dotted 1px;display: inline-block">
                    <a href="{{ url_for('collection.showView') }}">订阅中心</a>
                </div>
            </a>
            <div style="width: 50%;float: right">
                <a href="{{ url_for('user.passwordChangeView') }}?id={{ user.id }}">密码修改</a>
            </div>
        </div>
    </div>
</div>


        <!--其他区-->
        <div id="img"
             style="background: white;width: 70%;height: 280px;border: lightgrey solid 1px;border-left:none;margin-top: 10px;margin-left:-4px;float: right;margin-right: 10%">
            <img src="https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1543572339&di=f7fac3621aa5e4e88dc5fa05bc6ab874&imgtype=jpg&er=1&src=http%3A%2F%2Fs3.sinaimg.cn%2Fmw690%2F002hFK56gy6THuxxUjw22%26amp%3Bamp%3B690"
                 class="img-thumbnail">
            <img src="https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1542977534330&di=27832cf25925e4955eeff7926b3de62f&imgtype=0&src=http%3A%2F%2Fimg17.3lian.com%2Fd%2Ffile%2F201703%2F13%2Fa2e9bf2c4470e1e5a8ec5928e40e5d8e.jpg"
                 class="img-thumbnail">
            <img src="https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1542977425124&di=e477789453f826e30c2ff80e53502277&imgtype=0&src=http%3A%2F%2Fpic1.win4000.com%2Fwallpaper%2F2017-12-06%2F5a27d037376f4.jpg"
                 class="img-thumbnail">
            <div style="display: inline-block">岁月轮回 我们在寻觅什么</div>
            <div style="display: inline-block">可爱萌宠喵星人</div>
            <div style="display: inline-block">问世间 转过多少流年 ...</div>
        </div>


    <!--分页标签区-->
    <div style="background: white;width: 90%;height:280px;border: lightgrey solid 1px;margin-top: 15px">
        <div style="margin-top: 20px">

            <!-- Nav tabs -->
            <ul class="nav nav-tabs" role="tablist">
                <li role="presentation" class="active"><a href="#home" aria-controls="home" role="tab"
                                                          data-toggle="tab">Funs</a></li>
                <li role="presentation"><a href="#profile" aria-controls="profile" role="tab" data-toggle="tab">Chicken Soup</a>
                </li>
                <li role="presentation"><a href="#messages" aria-controls="messages" role="tab"
                                           data-toggle="tab">Messages</a>
                </li>
                <li role="presentation"><a href="#settings" aria-controls="settings" role="tab"
                                           data-toggle="tab">Music</a>
                </li>
            </ul>

            <!-- Tab panes -->
            <div class="tab-content">
                <div role="tabpanel" class="tab-pane active" id="home">
                    <ul style="margin-left:40px;width: 40%">
                        <li>
                            前些天嗓子病了，不能发声，领导却让我参加合唱比赛，给我说充个数就行。
                            我感觉这样不好，就积极治疗，赶在比赛前治好了。 结果比赛失利，领导一
                            声叹息的道：“你怎么偏偏赶在这时候嗓子好了呢？”
                        </li>
                    </ul>
                </div>
                <div role="tabpanel" class="tab-pane" id="profile">

                </div>
                <div role="tabpanel" class="tab-pane" id="messages">...</div>
                <div role="tabpanel" class="tab-pane" id="settings">
                    <div style="margin-top: 1%">
                        <div style="display: inline-block;width: 70px;">独孤天下:</div>
                        <div style="margin-top: 10px">
                        <audio controls style="">
                            <source src="horse.ogg" type="audio/ogg">
                            您的浏览器不支持 audio 元素。
                        </audio>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
{% endblock %}