apps/urls.py
"""
路由系统
"""
from flask_restful import Api

api = Api(prefix='/api/v1')

def init_api(app):
    api.init_app(app)

"""注册API路由系统"""
from apps.apis.indexapi import IndexApi

api.add_resource(IndexApi,'/index/',endpoint='index')

apps/news/views.py
from flask import Blueprint, render_template, request, redirect, url_for, session
from sqlalchemy import desc

from apps.user.models import User
from apps.collection.models import Collection
from apps.extend import db
from apps.news.models import Tag, News, NewsContentImg, Hot

news = Blueprint('news',__name__,template_folder='templates')

######主页#######
@news.route('/',methods=['get'])
def indexView():
    msg = request.args.get('msg')
    news = News.query.all()
    tags = Tag.query.all()
    hots = Hot.query.order_by(desc(Hot.count)).limit(7).all()
    for hot in hots:
        hotnews= News.query.filter_by(id=hot.nid).first()
        hot.new = hotnews

    try:
        del session['img_url']
    except:
        pass

    user = User.query.filter(User.username==session.get('username')).first()
    if user:
        img_url = user.img_url
        session['img_url'] = img_url
    # 组织上下文模板
    context = {
        'hots': hots,
        'news': news,
        'tags':tags,
        'msg': msg,
        'user':user
    }
    return render_template('index.html', **context)



######详情页#######
@news.route("/detail/",methods=['post','get'])
def detailView():
    message = request.args.get('message')
    id = request.args.get('nid')
    news = News.query.filter_by(id=id).first()
    user = User.query.filter_by(username=session.get('username')).first()
    bigimgs = NewsContentImg.query.filter_by(nid=id).first()
    collectnews = Collection.query.filter_by(nid=id).first()
    hotnews = Hot.query.filter_by(nid=id).first()
    if hotnews :
        hotnews.count += 1
    else:
        hotnews = Hot(nid=id,count=1)
    db.session.add(hotnews)
    db.session.commit()
    context = {
        'news': news,
        'bigimgs':bigimgs,
        'collectnews':collectnews,
        'user':user,
        'message':message,

    }
    return render_template('detail.html', **context)

######搜索页#######
@news.route("/search",methods = ['POST'])
def search():
    if not request.form['search']:
        return redirect(url_for('.index'))
    return redirect(url_for('.search_results', query=request.form['search']))


@news.route("/search_results/<query>")
def search_results(query):
    results = News.query.whoosh_search(query).all()
    print(results)
    return render_template('search_results.html', query=query, results=results)


######分类页#######
@news.route('/classify/',methods=['post','get'])
def classifyView():
    tid = request.args.get("tid")
    page = request.args.get("page",default=1,type=int)
    news = News.query.filter_by(tid=tid).paginate(page=page,per_page=5)
    context = {
        'pagination':news,
        'news':news.items,
        'tid':tid,
    }
    return render_template('classify.html',**context)

######今日热点######
@news.route('/todayhotnews/',methods=['post','get'])
def todayHotNews():
    news = News.query.order_by(desc(News.created_time)).limit(8)
    context = {
        'news': news,
    }
    return render_template('todayhotnews.html', **context)


# 赛选 多重赛选


# 富文本编辑
@news.route('/ckupload/',methods=['post','get'])
def ckUpload():
    return 'success'

apps/test_app/views.py
import base64
from flask import Blueprint, render_template, request, redirect, url_for, session,make_response
from apps.news.models import Tag, News
from apps.user.models import *
from apps.extend import login_manager
from flask_login import login_user
from io import BytesIO


test = Blueprint('test',__name__,template_folder='templates')

@test.route("/")
def index():
    # 在首页加载的时候创建索引
    # flask_whooshalchemyplus.index_one_model(News)

    news = News.query.all()
    tags = Tag.query.all()
    user = User.query.filter(User.username == session.get('username')).first()
    # 组织上下文模板
    context = {
        'news':news,
        'tags':tags,
        'user': user
    }
    return render_template('index_test.html',**context)

@test.route("/search",methods = ['POST'])
def search():
    if not request.form['search']:
        return redirect(url_for('.index'))
    return redirect(url_for('.search_results', query=request.form['search']))


@test.route("/search_results/<query>")
def search_results(query):
    results = News.query.whoosh_search(query).all()
    print(results)
    return render_template('search_results.html', query=query, results=results)


@login_manager.user_loader
def _login_user(id):
    return User.query.get(id)


@test.route("/login",methods=['post','get'])
def loginView():
    if request.method=='POST':
        username=request.form.get('username')
        password = request.form.get('password')
        ver_code=request.form.get('code_text').upper()
        ver_img=session.get('img')
        user = User.query.filter(User.username==username).first()
        if user:
            if user.password==user.vertify_password(password):
                login_user(user)
                msg = {

                }
                return render_template('index_base.html')
            else:
                return render_template('error.html')


@test.route('/code')
def code():
    from apps.test_app.Verification_code import create_validate_code
    code_img, strs = create_validate_code()

    buf = BytesIO()
    code_img.save(buf, 'jpeg')
    buf_str = buf.getvalue()
    response = make_response(buf_str)
    response.headers['Content-Type'] = 'image/jpeg'

    session['img'] = strs.upper()

    return response


@test.route('/showupload/')
def uploadShowView():
    return render_template('upload.html')

@test.route('/upload')
def uploadView():
    # a = request.args.get('data')
    # image = a.split(',')[1]
    # print(f'b:{image}')
    # fh = open("heiqie.jpeg", "wb")
    # fh.write(base64.b64decode(image))
    # fh.close()
    image_str = request.args.get('data').split(',')[1]
    username = session.get('username')
    path = './apps/static/upload/img/' + username + '.png'
    with open(path, "wb") as file:
        file.write(base64.b64decode(image_str))
    return 'aaa'

@test.route('/sendemail')
def sendEmailView():
    username = 'zl'
    to_email = 'm18361480741@163.com'
    uid = 1
    from apps.celery_tasks import send_register_active_email
    send_register_active_email.apply_async(to_email=to_email, username=username, uid=uid)
    return 'success'

@test.route('/sendemail')
def activeEmailView():
    return 'success activeEmailView'


@test.route('/404')
def View404():
    return render_template('404.html')

apps/user/views.py
import time
import base64

import flask_whooshalchemyplus
from flask import Blueprint, render_template, request, redirect, url_for,Flask, session,make_response
from apps.config import Config
from apps.news.models import Tag, Hot, News,NewsContentImg
from apps.user.models import *
from apps.extend import login_manager, mail,github
from flask_login import login_user, login_required
from io import BytesIO
from flask_mail import Message

from flask import jsonify

user = Blueprint('user', __name__,template_folder='templates')

'''用户中心'''


"""
Flask-Login要求程序实现一个回调函数，主要是获取存储到session中user对象
"""
@login_manager.user_loader
def load_user(id):
    """
    我们需要定义一个 LoginManager.user_loader 回调函数，
    它的作用是在用户登录并调用 login_user() 的时候, 根据 user_id 找到对应的 user, 如果没有找到，返回None,
    此时的 user_id 将会自动从 session 中移除, 若能找到 user ，则 user_id 会被继续保存
    :param id:
    :return:
    """
    return db.session.query(User).get(id)

# 登录
@user.route("/login",methods=['post','get'])
def loginView():
    if request.method=='POST':
        username=request.form.get('username')
        password = request.form.get('password')
        ver_code=request.form.get('code_text').upper()
        print(ver_code)
        ver_img=session.get('img')
        print(ver_img)
        if ver_img==ver_code:
            user = User.query.filter(User.username == username).first()
            if user:
                if user.vertify_password(password):
                    login_user(user)
                    session['username']=user.username
                    session['id']=user.id
                    session['img_url'] = user.img_url
                    return redirect(url_for('news.indexView'))
                else:
                    massage = '用户名或密码错误,请重新输入'
                    return redirect(url_for('news.indexView', msg=massage))
            else:
                massage='用户名或密码错误,请重新输入'
                return redirect(url_for('news.indexView',msg=massage))
        else:
            massage='验证码错误.请重新输入'
            return redirect(url_for('news.indexView',msg=massage))

@user.route('/ajax/',methods=['post'])
def ajaxHandle():
    username=request.values.get('name')
    user=User.query.filter(username==User.username).all()
    if user:
        return 'success'
    else:
        return ''

# 注册
@user.route('/register/',methods=['post','get'])
def registerView():

    # get方式返回注册页面
    if request.method == 'GET':
        return render_template('register.html')

    # post方式完成注册功能,并返回到首页
    elif request.method=='POST':

        # 获取数据
        username=request.form.get('username')
        password=request.form.get('password')
        email=request.form.get('email')
        phone=request.form.get('phone')
        user = User.query.filter(User.username == username).all()

        # 该用户未被注册,将信息保存,完成注册
        if not user:
            try:
                user = User()
                user.username = username
                user.email = email
                user.phone = phone
                # 将密码加密并保存
                user.passwordHandle=password
                db.session.add(user)
                db.session.commit()
            # 有错误,回滚
            except:
                db.session.rollback()
                return render_template('404.html')
        else:
            return render_template('register.html', msg='该用户名已被注册')
        # 注册成功,返回首页
        return redirect(url_for('news.indexView'))
    else:
        return render_template('404.html')



# 登出
@user.route('/logout/',methods=['post','get'])
def logoutView():
    del session['username']
    del session['id']
    return redirect(url_for('news.indexView'))

# 用户激活
@user.route('/activate/',methods=['post','get'])
def activateView():
    pass


#  发送邮件:密码修改前的验证
@user.route('/emailSend/',methods=['post','get'])
def emailSendView():

    # 先获取用户邮箱信息,用于验证
    if request.method=='GET':
        return render_template('/user_info_change/email_check.html')

    # 给用户发送邮件,完成验证
    elif request.method=='POST':
        email=request.form.get('email')
        user=User.query.filter(User.email==email).first()
        # 如果邮箱正确,发送邮件
        if user:
            try:
                msg = Message(subject="邮箱验证",
                              sender=Config.MAIL_USERNAME,
                              recipients=["13781041970@163.com"])

                context = {
                    'name': user.username,
                    'id': user.id
                }
                msg.html = render_template('/user_info_change/send_for_email_check.html', **context)
                mail.send(msg)
                return redirect(url_for('news.indexView'))
            except Exception as e:
                return redirect(url_for('test.View404'))
        else:
            return render_template('/user_info_change/email_check.html',msg='该邮箱未被注册')


@user.route('/passwordChange/',methods=['post','get'])
def passwordChangeView():
    if request.method=='GET':
        id=request.args.get('id')
        user=User.query.filter(User.id==id).first()
        return render_template('/user_info_change/passwordChange.html',username=user.username,id=id)
    elif request.method=='POST':
        id=request.form.get('id')
        password=request.form.get('password')
        user=User.query.filter(User.id==id).first()
        user.passwordHandle=password
        db.session.commit()
        login_user(user)
        session['username'] = user.username
        session['id'] = user.id
        return redirect(url_for('news.indexView'))
    else:
        return '404 错误的请求方式'

@user.route('/code')
def code():
    from apps.test_app.Verification_code import create_validate_code
    code_img, strs = create_validate_code()
    buf = BytesIO()
    code_img.save(buf, 'jpeg')
    buf_str = buf.getvalue()
    response = make_response(buf_str)
    response.headers['Content-Type'] = 'image/jpeg'
    session['img'] = strs.upper()
    return response


# 管理后台用户登录
@user.route('/authlogin/',methods=['post'])
def authUserLogin():
    authname = request.form.get('authname')
    authpwd = request.form.get('authpwd')
    user = User.query.filter(User.username == 'zenglong').first()
    if authname == 'zenglong':
        if user.vertify_password(authpwd):
            login_user(user)
            session['authname'] = authname
            return redirect(url_for('admin.index'))
        else:
            context = {
                'msg' : '用户名或密码错误'
            }
            return render_template('admin/authlogin.html',**context)
    else:
        context = {
            'msg': '没有此用户'
        }
        return render_template('admin/authlogin.html',**context)

# 头像上传
@user.route('/showupload/')
def uploadShowView():
    return render_template('upload.html')

@user.route('/upload/')
def uploadView():
    image_str = request.args.get('data').split(',')[1]
    username = session.get('username')
    path = './apps/static/upload/img/' + username + '.png'
    with open(path, "wb") as file:
        file.write(base64.b64decode(image_str))

    user_img_url = '/static/upload/img/' + username + '.png'
    user = User.query.filter(User.username==username).first()
    user.img_url = user_img_url
    db.session.commit()

    # 如果用户更换头像,先清除session中的img_url
    if session.get('img_url',None):
        del session['img_url']

    return 'success'


# 用户中心
@user.route('/user_info/',methods=['post','get'])
def userInfoView():
    id=session.get('id')
    user=User.query.filter(User.id==id).first()
    tags = Tag.query.all()
    context={
        'user':user,
        'tags':tags
    }
    return render_template('user_info.html',**context)

apps/test_app/templates/index_test.html
{% extends 'index_base.html' %}
{% block css %}
    <style>
        /* Custom Styles */
        ul.nav-tabs {
            width: 150px;
            height: 100%;
        }
    </style>
{% endblock %}

{% block catagory %}
    <div style="width: 100%;background-color: green;">
        <div class="col-xs-3" id="myScrollspy">
            <div>
                <ul class="nav nav-tabs nav-stacked" data-offset-top="125">
                    <li><img src="/static/logo/logo.jpg" style="width: 145px;height: 100px"></li>
                    {% for tag in tags %}
                        <li class="bg-info"><a href="#" style="height:70px;font-size: 29px"
                                               class="text-center">{{ tag.t_name }}</a></li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
{% endblock %}

{% block banner %}
    <div style="width: 100%;height:400px;background-color: #5bc0de;">
        <div id="slidershow" class="carousel slide" data-ride="carousel"
             style="position: relative;clear: both">
            <!-- 设置图片轮播的顺序 -->
            <ol class="carousel-indicators">
                <li class="active" data-target="#slidershow" data-slide-to="0">
                <li data-target="#slidershow" data-slide-to="1">
                <li data-target="#slidershow" data-slide-to="2">
            </ol>
            <!-- 设置轮播图片 -->
            <div class="carousel-inner">
                <div class="item active">
                    <a href="#"><img src="{{ url_for('static',filename='banner/1.jpg') }}"
                                     style="height: 400px;width: 100%"></a>
                    <div class="carousel-caption" style="font-size: large">习近平同巴布亚新几内亚总理奥尼尔会谈</div>
                </div>
                <div class="item">
                    <a href="#"><img src="{{ url_for('static',filename='banner/2.jpg') }}"
                                     style="height: 400px;width: 100%"></a>
                    <div class="carousel-caption" style="font-size: large">青海西宁降下大雪 道路结冰影响市民出行</div>
                </div>
                <div class="item">
                    <a href="#"><img src="{{ url_for('static',filename='banner/3.jpg') }}"
                                     style="height: 400px;width: 100%"></a>
                    <div class="carousel-caption" style="font-size: large">5岁男孩一次做4105个俯卧撑 获赠奔驰车</div>
                </div>
            </div>
            <!-- 设置轮播图片控制器 -->
            <a class="left carousel-control" href="#slidershow" role="button" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left"></span>
            </a>
            <a class="right carousel-control" href="#slidershow" role="button" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right"></span>
            </a>
        </div>

    </div>
{% endblock %}


{% block newslist %}
    <div style="width: 100%;height:1000px;">
        {#        {% for new in news %}#}
        {#            <div>#}
        {#                <img src="{{ new.img_url }}" style="width: 100%;">#}
        {#                <div><h3>{{ new.title }}</h3></div>#}
        {#            </div>#}
        {#        {% endfor %}#}
        <table class="table">
            {% for new in news %}
                <tr>
                    <th  class="col-md-3" ><a href="{{ url_for('news.detailView') }}?id={{ new.id }}"><img src="{{ new.img_url }}" style="height: 100px;width: 158px"></a></th>
                    <th  class="col-md-9" ><a href="{{ url_for('news.detailView') }}?id={{ new.id }}"><h3 >{{ new.title }}</h3></a></th>
                </tr>
            {% endfor %}
        </table>
    </div>

{% endblock %}


{% block user %}
    <div style="width:100%;height: auto;">
        <div style="width:100%">
            <div style="width:100%;height: auto;border: lightgray solid 1px;border-radius:4px;">
                <form class="navbar-form navbar-left" style="width: inherit;padding: 0;">
                    <div class="form-group" style="display: inline-block;width: 69%;margin-left: 10px">
                        <input type="text" class="form-control" placeholder="搜索" style="width:100%">
                    </div>
                    <button type="submit" class="btn btn-default" style="margin-right: 10px;margin-left:3px;width: 20%"><span class="glyphicon glyphicon-search"></span>
                    </button>
                </form>
                <br>
                <br>
                <br>
                <div style="margin-top:-9px;border-top: lightgray solid 1px;">
                    <div style="width: inherit;height: 30px;text-align: center;">
                        <h4><strong>账号密码登陆</strong></h4>
                    </div>
                    <form class="form-horizontal" role="form" style="width: inherit;padding: 0;" action="{{ url_for('test.loginView') }}" method="post">
                        <div class="form-group" style="width: 100%;margin: 0">
                            <label for="firstname" class="col-sm-4 control-label" style="width:32%;margin: 0;">用户名:</label>
                            <input type="text" style="width: 64%;" class="form-control" id="firstname" placeholder="请输入用户名" name="username">
                        </div>
                        <div class="form-group" style="width: 100%;margin: 0;margin-top: 7px">
                            <label for="lastname" class="col-sm-4 control-label" style="width:32%;display: inline-block">密码:</label>
                            <input type="text" style="width: 64%" class=" form-control" id="lastname" placeholder="请输入密码" name="password">
                        </div>
                        <div  class="form-group" style="width: 100%;margin: 0;margin-top: 7px">
                            <label  class="col-sm-4 control-label" style="width:32%;display: inline-block">验证码</label>
                            <input type="text" style="width: 64%" class="form-control" id="code1" placeholder="请输入验证码" name="code_text">
                            <img id="code" src="{{ url_for('test.code') }}" onclick="ajax1()" style="margin-left: 90px;margin-top: 10px">
                            <p style="margin-left: 50px">点击图片即可刷新验证码</p>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <div class="checkbox">
                                    <label>
                                        <input type="checkbox">请记住我
                                        <a href="{{ url_for('user.emailSendView')}}" style="text-decoration: none;margin-left: 7px"><span>忘记密码?</span></a>
                                    </label>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-info">登录</button>
                                <a href="{{ url_for('user.registerView') }}" style="margin-left: 5px">
                                    <button type="button" class="btn btn-default">注册</button>
                                </a>

                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
<script>
        function ajax1() {
            var xhr = new XMLHttpRequest();
            xhr.open('GET', "{{ url_for('test.code') }}",true);
            xhr.onreadystatechange = function () {
                if (xhr.readyState == 4){
                    $('#code').attr('src',"{{ url_for('test.code') }}?"+Math.random())
                }
            };
            xhr.send()
        }
    </script>
{% endblock %}

{% block hot %}
    <div style="width:100%;height: 800px;background-color: yellow">

    {#  测试富文本  #}
    <div>
    <h1>完整demo</h1>
    <textarea id="content" class="ckeditor"></textarea>
    </div>

    <script type="text/javascript">
    CKEDITOR.replace('content', {
    filebrowserUploadUrl: '/ckupload/',
    });
    </script>

        <div class="pane-module hot-words-pane">
            <a class="list-group-item active">
                <h4 style="font-weight:bold">热搜新闻</h4>
            </a>
            <a href="https://m.toutiao.com/search/?keyword=%E6%B2%B9%E4%BB%B7%20%E5%9B%9B%E5%B9%B4%E6%9C%80%E5%A4%A7%E8%B7%8C%E5%B9%85&from=gs_hotlist"
               class="list-group-item">1 油价 四年最大跌幅</a>
            <a href="https://m.toutiao.com/search/?keyword=%E6%B4%97%E5%AE%8C%E5%A4%B4%E7%BB%93%E8%B4%A617000%E5%85%83&from=gs_hotlist"
               class="list-group-item">2 洗完头结账17000元</a>
            <a href="https://m.toutiao.com/search/?keyword=%E9%A9%AC%E8%93%89%E5%86%8D%E5%96%8A%E8%AF%9D%E7%8E%8B%E5%AE%9D%E5%BC%BA&from=gs_hotlist"
               class="list-group-item">3 马蓉再喊话王宝强</a>
            <a href="https://m.toutiao.com/search/?keyword=%E8%81%82%E6%A0%91%E6%96%8C%E6%AF%8D%E4%BA%B2%E5%8F%91%E5%A3%B0&from=gs_hotlist"
               class="list-group-item">4 聂树斌母亲发声</a>
            <a href="https://m.toutiao.com/search/?keyword=%E9%82%93%E8%B6%85%E5%AD%99%E4%BF%AA%20%E9%87%91%E9%A9%AC%E5%A5%96&from=gs_hotlist"
               class="list-group-item">5 邓超孙俪 金马奖
                <img src="//s3.pstatp.com/toutiao/static/img/icon_hot_search_t2.4c778ee.png" alt style="float: right"
                     height="20px">
            </a>
            <a href="https://m.toutiao.com/search/?keyword=%E5%A9%9A%E7%A4%BC%E7%8E%B0%E5%9C%BA%E7%88%86%E7%82%B8%E8%87%B41%E6%AD%BB&from=gs_hotlist"
               class="list-group-item">6 婚礼现场爆炸致1死</a>
            <a href="https://m.toutiao.com/search/?keyword=%E6%9D%A8%E7%B4%AB%E7%A9%BF%E9%AB%98%E8%B7%9F%E9%9E%8B%E6%91%94%E5%80%92&from=gs_hotlist"
               class="list-group-item">7 杨紫穿高跟鞋摔倒
                <img src="//s3.pstatp.com/toutiao/static/img/icon_hot_search_t2.4c778ee.png" alt style="float: right"
                     height="20px">
            </a>
        </div>
        <div class="pane-module hot-words-pane">
            <a class="list-group-item active">
                <h4 style="font-weight:bold">24小时热闻</h4></a>
            <a href="https://www.toutiao.com/group/6624658828648513795/" class="list-group-item">
                <div class="media">
                    <div class="media-left">
                        <img src="//p99.pstatp.com/list/240x240/da930002dd377261adf6" class="media-object"
                             style="width:60px"></div>
                    <div class="media-body" style="padding: 10px">
                        选三缸福克斯还是四缸高尔夫？广州车展找答案
                    </div>
                </div>
            </a>
            <a href="https://www.toutiao.com/group/6618359724360335620/" class="list-group-item">
                <div class="media">
                    <div class="media-left">
                        <img src="https://p3.pstatp.com/list/240x240/dab70000a6710e337062" class="media-object"
                             style="width:60px">
                    </div>
                    <div class="media-body" style="padding: 10px">
                        2018今日头条生机大会
                    </div>
                </div>
            </a>
            <a href="https://www.toutiao.com/group/6624417815111696904/" class="list-group-item">
                <div class="media">
                    <div class="media-left">
                        <img src="https://p1.pstatp.com/list/240x240/pgc-image/a452e01cdcfe41b386cbe0c807f20e4c"
                             class="media-object"
                             style="width:60px">
                    </div>
                    <div class="media-body" style="padding: 10px">
                        易到回应高管给CEO磕头风波：遭险恶有预谋饭局 已向警方报案
                    </div>
                </div>
            </a>
            <a href="https://www.toutiao.com/group/6624687499392320007/" class="list-group-item">
                <div class="media">
                    <div class="media-left">
                        <img src="https://p1.pstatp.com/list/240x240/pgc-image/R9dA5RDFlzBJyu" class="media-object"
                             style="width:60px">
                    </div>
                    <div class="media-body" style="padding: 10px">
                        枪枪毙命：美国德州农场主用夜视仪狙击枪击毙45头郊狼
                    </div>
                </div>
            </a>
        </div>
    </div>
{% endblock %}

<script type="text/javascript">
    $(window).height()

</script>

apps/test_app/templates/mail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>激活邮件</title>
</head>
<body>
<h2>{{ username }}你好,欢迎来到新闻网邮件激活</h2>
<a href="{{ url_for('test.activeEmailView') }}?token={{ token }}">立即激活</a>
</body>
</html>

apps/test_app/templates/search_results.html
{% extends 'base.html' %}


{% block content %}

    <h1 style="color: red">搜索关键词： "{{query}}"</h1>

    {% for result in results %}
    <div class="col-md-11" style="margin-bottom: 30px">
        <div class="text-center"><img src="{{ result.img_url }}" style="width: 500px"></div>
        <div style="font-size: 30px" >{{ result.title }}</div>
        <div style="font-size: 20px">{{ result.content }}</div>
    </div>
    {% endfor %}



{% endblock %}