apps/urls.py
"""
路由系统
"""
from flask_restful import Api

api = Api(prefix='/api/v1')

def init_api(app):
    api.init_app(app)

"""注册API路由系统"""
from apps.apis.indexapi import IndexApi

api.add_resource(IndexApi,'/index/',endpoint='index')

apps/collection/views.py
import datetime
from flask import Blueprint, session, request, redirect, url_for,render_template
from sqlalchemy import and_

from apps.collection.models import Collection
from apps.extend import db
from apps.news.models import News

collection = Blueprint('collection', __name__,template_folder='templates')

'''收藏页'''


# 展示收藏
@collection.route('/show/',methods=['post','get'])
def showView():

    if request.method=='GET':
        uid=session.get('id')
        if uid:
            collection_news = Collection.query.filter( and_(Collection.uid==uid,Collection.is_delete==0)).all()
            for collection_new in collection_news:
                new=News.query.filter(News.id==collection_new.nid).first()
                collection_new.new = new
            #组织桑下文模板
            context = {
                'collection_news':collection_news
            }
            return render_template('collectview.html',**context)


# 添加到收藏
@collection.route('/add/',methods=['post','get'])
def addView():
    nid = request.args.get('nid')
    uid = request.args.get('uid')
    collectnews = Collection.query.filter_by(nid=nid,uid=uid).first()
    if collectnews:
        message = '您已经收藏了!~'
    else:
        collectnews =Collection(uid=uid, nid=nid,is_delete=0)
        message = '收藏成功!~'
    db.session.add(collectnews)
    db.session.commit()

    return redirect(url_for('news.detailView',nid=nid,uid=uid,message=message))
# 删除收藏
@collection.route('/delete/',methods=['post','get'])
def deleteView():
    nid = request.args.get('nid')
    uid = session.get('id')
    collectnews = Collection.query.filter_by(nid=nid,uid=uid).first()
    if collectnews:
        collectnews.is_delete = 1
        db.session.commit()
        message = '收藏成功!~'
    else:
        message = '您未收藏!~'

    return redirect(url_for('news.detailView',nid=nid,uid=uid,message=message))



# 收藏内容
@collection.route('/collect/',methods=['post','get'])
def collectionView():
    pass

apps/githubuser/views.py
from flask import Flask, request, g, session, redirect, url_for, render_template, jsonify, flash, Blueprint
from sqlalchemy import and_, desc
from apps.extend import github, db
from apps.githubuser.models import Gituser
from apps.news.models import News, Hot, Tag

githubuser = Blueprint('githubuser', __name__,template_folder='templates')

@githubuser.before_request
def before_request():
    g.user = None
    if 'user_id' in session:
        g.user = Gituser.query.get(session['user_id'])

# 创建登录按钮
@githubuser.route('/')
def index():
    if g.user:
        is_login = True
        response = github.get('user')
        avatar = response['avatar_url']
        username = response['name']
        url = response['html_url']

        news = News.query.all()
        tags = Tag.query.all()
        hots = Hot.query.order_by(desc(Hot.count)).limit(7).all()
        for hot in hots:
            hotnews = News.query.filter_by(id=hot.nid).first()
            hot.new = hotnews

        # 组织上下文模板
        context = {
            'is_login' : is_login,
            'avatar' : avatar,
            'username' : username,
             'url' : url,
            'hots': hots,
            'news': news,
            'tags': tags,
        }
        return render_template('index.html',**context )

    # 如果未登录
    is_login = False
    context = {
        'is_login': is_login,
    }
    return render_template('gitindex.html',**context)

# 因为我们在进行授权时请求了repo权限，我们还可以对用户的仓库进行各类操作
@githubuser.route('/star/helloflask')
def star():
    github.put('user/starred/greyli/helloflask', headers={'Content-Length': '0'})
    flash('Star success.')
    return redirect(url_for('.index'))

# 因为我们需要在其他视图里调用GitHub资源，为了避免每次都获取和传入访问令牌，
# 我们可以使用github.access_token_getter装饰器创建一个统一的令牌获取函数：
# 当你在某处直接使用github.get()等方法而不传入访问令牌时，
# GitHub-Flask会通过你提供的这个回调函数来获取访问令牌。
@github.access_token_getter
def token_getter():
    user = g.user
    if user is not None:
        return user.github_access_token

# 获取access令牌（访问令牌）
@githubuser.route('/callback/github/')
@github.authorized_handler
def authorized(access_token):
    print(access_token)
    if access_token is None:
        flash('Login failed.')
        return redirect(url_for('.index'))

    # 创建新用户，保存访问令牌，登入用户等操作

    # 获取响应信息,github返回一个字典
    response = github.get('user', access_token=access_token)
    # 得到github用户名
    username = response['login']
    user = Gituser.query.filter_by(username=username).first()

    if user is None:
        # user = Gituser(username=username, github_access_token=access_token)
        user = Gituser(access_token)
        user.username = username
        user.github_access_token = access_token
        db.session.add(user)
    user.github_access_token = access_token  # update access token
    db.session.commit()
    flash('Login success.')
    # log the user in
    # if you use flask-login, just call login_user() here.
    session['user_id'] = user.id
    return redirect(url_for('.index'))

# 登入
@githubuser.route('/login')
def login():
    # print(session.get('user_id'))
    # 如果用户没有登录
    if session.get('user_id', None) is None:
        return github.authorize(scope='repo')
    # 如果用户已经登录
    flash('Already logged in.')
    return redirect(url_for('.index'))

# 登出
@githubuser.route('/logout')
def logout():
    session.pop('user_id', None)
    flash('Goodbye.')
    return redirect(url_for('.index'))

# 对应用户资料，返回的 JSON 数据
@githubuser.route('/user')
def get_user():
    return jsonify(github.get('user'))




'''
/user端点对应用户资料，返回的 JSON 数据如下所示：
{
 "avatar_url": "https://avatars3.githubusercontent.com/u/12967000?v=4", 
 "bio": null, 
 "blog": "greyli.com", 
 "company": "None", 
 "created_at": "2015-06-19T13:00:23Z", 
 "email": "withlihui@gmail.com", 
 "events_url": "https://api.github.com/users/greyli/events{/privacy}", 
 "followers": 132, 
 "followers_url": "https://api.github.com/users/greyli/followers", 
 "following": 8, 
 "following_url": "https://api.github.com/users/greyli/following{/other_user}", 
 "gists_url": "https://api.github.com/users/greyli/gists{/gist_id}", 
 "gravatar_id": "", 
 "hireable": true, 
 "html_url": "https://github.com/greyli", 
 "id": 12967000, 
 "location": "China", 
 "login": "greyli", 
 "name": "Grey Li", 
 "node_id": "MDQ6VXNlcjEyOTY3MDAw", 
 "organizations_url": "https://api.github.com/users/greyli/orgs", 
 "public_gists": 7, 
 "public_repos": 61, 
 "received_events_url": "https://api.github.com/users/greyli/received_events", 
 "repos_url": "https://api.github.com/users/greyli/repos", 
 "site_admin": false, 
 "starred_url": "https://api.github.com/users/greyli/starred{/owner}{/repo}", 
 "subscriptions_url": "https://api.github.com/users/greyli/subscriptions", 
 "type": "User", 
 "updated_at": "2018-06-24T02:05:38Z", 
 "url": "https://api.github.com/users/greyli"
}复制代码
'''

apps/news/views.py
from flask import Blueprint, render_template, request, redirect, url_for, session
from sqlalchemy import desc

from apps.user.models import User
from apps.collection.models import Collection
from apps.extend import db
from apps.news.models import Tag, News, NewsContentImg, Hot

news = Blueprint('news',__name__,template_folder='templates')

######主页#######
@news.route('/',methods=['get'])
def indexView():
    msg = request.args.get('msg')
    news = News.query.all()
    tags = Tag.query.all()
    hots = Hot.query.order_by(desc(Hot.count)).limit(7).all()
    for hot in hots:
        hotnews= News.query.filter_by(id=hot.nid).first()
        hot.new = hotnews

    try:
        del session['img_url']
    except:
        pass

    user = User.query.filter(User.username==session.get('username')).first()
    if user:
        img_url = user.img_url
        session['img_url'] = img_url
    # 组织上下文模板
    context = {
        'hots': hots,
        'news': news,
        'tags':tags,
        'msg': msg,
        'user':user
    }
    return render_template('index.html', **context)



######详情页#######
@news.route("/detail/",methods=['post','get'])
def detailView():
    message = request.args.get('message')
    id = request.args.get('nid')
    news = News.query.filter_by(id=id).first()
    user = User.query.filter_by(username=session.get('username')).first()
    bigimgs = NewsContentImg.query.filter_by(nid=id).first()
    collectnews = Collection.query.filter_by(nid=id).first()
    hotnews = Hot.query.filter_by(nid=id).first()
    if hotnews :
        hotnews.count += 1
    else:
        hotnews = Hot(nid=id,count=1)
    db.session.add(hotnews)
    db.session.commit()
    context = {
        'news': news,
        'bigimgs':bigimgs,
        'collectnews':collectnews,
        'user':user,
        'message':message,

    }
    return render_template('detail.html', **context)

######搜索页#######
@news.route("/search",methods = ['POST'])
def search():
    if not request.form['search']:
        return redirect(url_for('.index'))
    return redirect(url_for('.search_results', query=request.form['search']))


@news.route("/search_results/<query>")
def search_results(query):
    results = News.query.whoosh_search(query).all()
    print(results)
    return render_template('search_results.html', query=query, results=results)


######分类页#######
@news.route('/classify/',methods=['post','get'])
def classifyView():
    tid = request.args.get("tid")
    page = request.args.get("page",default=1,type=int)
    news = News.query.filter_by(tid=tid).paginate(page=page,per_page=5)
    context = {
        'pagination':news,
        'news':news.items,
        'tid':tid,
    }
    return render_template('classify.html',**context)

######今日热点######
@news.route('/todayhotnews/',methods=['post','get'])
def todayHotNews():
    news = News.query.order_by(desc(News.created_time)).limit(8)
    context = {
        'news': news,
    }
    return render_template('todayhotnews.html', **context)


# 赛选 多重赛选


# 富文本编辑
@news.route('/ckupload/',methods=['post','get'])
def ckUpload():
    return 'success'

apps/user/views.py
import time
import base64

import flask_whooshalchemyplus
from flask import Blueprint, render_template, request, redirect, url_for,Flask, session,make_response
from apps.config import Config
from apps.news.models import Tag, Hot, News,NewsContentImg
from apps.user.models import *
from apps.extend import login_manager, mail,github
from flask_login import login_user, login_required
from io import BytesIO
from flask_mail import Message

from flask import jsonify

user = Blueprint('user', __name__,template_folder='templates')

'''用户中心'''


"""
Flask-Login要求程序实现一个回调函数，主要是获取存储到session中user对象
"""
@login_manager.user_loader
def load_user(id):
    """
    我们需要定义一个 LoginManager.user_loader 回调函数，
    它的作用是在用户登录并调用 login_user() 的时候, 根据 user_id 找到对应的 user, 如果没有找到，返回None,
    此时的 user_id 将会自动从 session 中移除, 若能找到 user ，则 user_id 会被继续保存
    :param id:
    :return:
    """
    return db.session.query(User).get(id)

# 登录
@user.route("/login",methods=['post','get'])
def loginView():
    if request.method=='POST':
        username=request.form.get('username')
        password = request.form.get('password')
        ver_code=request.form.get('code_text').upper()
        print(ver_code)
        ver_img=session.get('img')
        print(ver_img)
        if ver_img==ver_code:
            user = User.query.filter(User.username == username).first()
            if user:
                if user.vertify_password(password):
                    login_user(user)
                    session['username']=user.username
                    session['id']=user.id
                    session['img_url'] = user.img_url
                    return redirect(url_for('news.indexView'))
                else:
                    massage = '用户名或密码错误,请重新输入'
                    return redirect(url_for('news.indexView', msg=massage))
            else:
                massage='用户名或密码错误,请重新输入'
                return redirect(url_for('news.indexView',msg=massage))
        else:
            massage='验证码错误.请重新输入'
            return redirect(url_for('news.indexView',msg=massage))

@user.route('/ajax/',methods=['post'])
def ajaxHandle():
    username=request.values.get('name')
    user=User.query.filter(username==User.username).all()
    if user:
        return 'success'
    else:
        return ''

# 注册
@user.route('/register/',methods=['post','get'])
def registerView():

    # get方式返回注册页面
    if request.method == 'GET':
        return render_template('register.html')

    # post方式完成注册功能,并返回到首页
    elif request.method=='POST':

        # 获取数据
        username=request.form.get('username')
        password=request.form.get('password')
        email=request.form.get('email')
        phone=request.form.get('phone')
        user = User.query.filter(User.username == username).all()

        # 该用户未被注册,将信息保存,完成注册
        if not user:
            try:
                user = User()
                user.username = username
                user.email = email
                user.phone = phone
                # 将密码加密并保存
                user.passwordHandle=password
                db.session.add(user)
                db.session.commit()
            # 有错误,回滚
            except:
                db.session.rollback()
                return render_template('404.html')
        else:
            return render_template('register.html', msg='该用户名已被注册')
        # 注册成功,返回首页
        return redirect(url_for('news.indexView'))
    else:
        return render_template('404.html')



# 登出
@user.route('/logout/',methods=['post','get'])
def logoutView():
    del session['username']
    del session['id']
    return redirect(url_for('news.indexView'))

# 用户激活
@user.route('/activate/',methods=['post','get'])
def activateView():
    pass


#  发送邮件:密码修改前的验证
@user.route('/emailSend/',methods=['post','get'])
def emailSendView():

    # 先获取用户邮箱信息,用于验证
    if request.method=='GET':
        return render_template('/user_info_change/email_check.html')

    # 给用户发送邮件,完成验证
    elif request.method=='POST':
        email=request.form.get('email')
        user=User.query.filter(User.email==email).first()
        # 如果邮箱正确,发送邮件
        if user:
            try:
                msg = Message(subject="邮箱验证",
                              sender=Config.MAIL_USERNAME,
                              recipients=["13781041970@163.com"])

                context = {
                    'name': user.username,
                    'id': user.id
                }
                msg.html = render_template('/user_info_change/send_for_email_check.html', **context)
                mail.send(msg)
                return redirect(url_for('news.indexView'))
            except Exception as e:
                return redirect(url_for('test.View404'))
        else:
            return render_template('/user_info_change/email_check.html',msg='该邮箱未被注册')


@user.route('/passwordChange/',methods=['post','get'])
def passwordChangeView():
    if request.method=='GET':
        id=request.args.get('id')
        user=User.query.filter(User.id==id).first()
        return render_template('/user_info_change/passwordChange.html',username=user.username,id=id)
    elif request.method=='POST':
        id=request.form.get('id')
        password=request.form.get('password')
        user=User.query.filter(User.id==id).first()
        user.passwordHandle=password
        db.session.commit()
        login_user(user)
        session['username'] = user.username
        session['id'] = user.id
        return redirect(url_for('news.indexView'))
    else:
        return '404 错误的请求方式'

@user.route('/code')
def code():
    from apps.test_app.Verification_code import create_validate_code
    code_img, strs = create_validate_code()
    buf = BytesIO()
    code_img.save(buf, 'jpeg')
    buf_str = buf.getvalue()
    response = make_response(buf_str)
    response.headers['Content-Type'] = 'image/jpeg'
    session['img'] = strs.upper()
    return response


# 管理后台用户登录
@user.route('/authlogin/',methods=['post'])
def authUserLogin():
    authname = request.form.get('authname')
    authpwd = request.form.get('authpwd')
    user = User.query.filter(User.username == 'zenglong').first()
    if authname == 'zenglong':
        if user.vertify_password(authpwd):
            login_user(user)
            session['authname'] = authname
            return redirect(url_for('admin.index'))
        else:
            context = {
                'msg' : '用户名或密码错误'
            }
            return render_template('admin/authlogin.html',**context)
    else:
        context = {
            'msg': '没有此用户'
        }
        return render_template('admin/authlogin.html',**context)

# 头像上传
@user.route('/showupload/')
def uploadShowView():
    return render_template('upload.html')

@user.route('/upload/')
def uploadView():
    image_str = request.args.get('data').split(',')[1]
    username = session.get('username')
    path = './apps/static/upload/img/' + username + '.png'
    with open(path, "wb") as file:
        file.write(base64.b64decode(image_str))

    user_img_url = '/static/upload/img/' + username + '.png'
    user = User.query.filter(User.username==username).first()
    user.img_url = user_img_url
    db.session.commit()

    # 如果用户更换头像,先清除session中的img_url
    if session.get('img_url',None):
        del session['img_url']

    return 'success'


# 用户中心
@user.route('/user_info/',methods=['post','get'])
def userInfoView():
    id=session.get('id')
    user=User.query.filter(User.id==id).first()
    tags = Tag.query.all()
    context={
        'user':user,
        'tags':tags
    }
    return render_template('user_info.html',**context)

apps/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {#  建议都用动态路由解析  #}
    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='bootstrap/css/bootstrap.css') }}">
    {#<link rel="stylesheet" type="text/css" href="/static/bootstrap/css/bootstrap.css">#}
    <script src="{{ url_for('static',filename='bootstrap/js/jquery-1.12.4.min.js') }}"></script>
    {#<script  src="/apps/static/bootstrap/js/jquery-1.12.4.min.js"></script>#}
    <script src="{{ url_for('static',filename='bootstrap/js/bootstrap.min.js') }}"></script>
    {#<script  src="/apps/static/bootstrap/js/bootstrap.min.js"></script>#}
    {#  导入CKeditor  #}
{#    <script src="{{ url_for('static', filename='ckeditor/ckeditor.js') }}"></script>#}
    <script  src="//cdn.ckeditor.com/4.4.6/standard/ckeditor.js"></script>
    <script>
        function showTime() {
            var show_day = new Array('星期日', '星期一', '星期二', '星期三', '星期四', '星期五', '星期六');
            var time = new Date();
            var year = time.getYear();
            if (year < 1000) {
                year += 1900;
            }
            var month = time.getMonth();
            var date = time.getDate();
            var day = time.getDay();
            var hour = time.getHours();
            var minutes = time.getMinutes();
            var second = time.getSeconds();
            var dn = "AM";
            if (hour >= 12) {
                dn = "PM";
            }

            month = month + 1;
            month < 10 ? month = '0' + month : month;
            hour < 10 ? hour = '0' + hour : hour;
            minutes < 10 ? minutes = '0' + minutes : minutes;
            second < 10 ? second = '0' + second : second;
            var now_time = year + '年' + month + '月' + date + '日' + ' ' + show_day[day] + ' ' + hour + ':' + minutes + ':' + second + " " + dn;
            document.getElementById('showtime').innerHTML = now_time;
            setTimeout("showTime();", 1000);
        }

    </script>


    <!-- css 预留版块，提供给子模板扩展 -->
    {% block css %}{% endblock %}
</head>


<body onload="showTime()">
<!-- 导航栏 可自行扩展 -->
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url_for('news.indexView') }}"><span
                    class="glyphicon glyphicon-home"></span>&nbsp;&nbsp;首&nbsp;&nbsp;页&nbsp;&nbsp;</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class="active"><a href="#" id="showtime"><span class="sr-only">(current)</span></a></li>
                <!--  左下拉菜单start  -->
                {#        <li class="dropdown">#}
                {#          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>#}
                {#          <ul class="dropdown-menu">#}
                {#            <li><a href="#">Action</a></li>#}
                {#            <li><a href="#">Another action</a></li>#}
                {#            <li><a href="#">Something else here</a></li>#}
                {#            <li role="separator" class="divider"></li>#}
                {#            <li><a href="#">Separated link</a></li>#}
                {#            <li role="separator" class="divider"></li>#}
                {#            <li><a href="#">One more separated link</a></li>#}
                {#          </ul>#}
                {#        </li>#}
                <!--  左下拉菜单end  -->

            </ul>
            <form class="navbar-form navbar-left" action="{{ url_for('news.search') }}" method="POST">
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="Search" name="search">
                </div>
                <button type="submit" class="btn btn-default">搜&nbsp;&nbsp;索</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
                {% if session.username %}
                    {% if session.img_url %}
                        <li><a href="#"><img src="{{ session.img_url }}" style="height: 20px"></a></li>
                    {% else %}
                        <li><a href="{{ url_for('user.uploadShowView') }}"><span class="glyphicon glyphicon-user"></span>头像上传</a></li>

                    {% endif %}
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                           aria-expanded="false">{{ session.username }}<span class="caret"></span></a>
                        <ul class="dropdown-menu" style="font-size: medium">
                            <li><a href="{{ url_for('user.userInfoView') }}"><span class="glyphicon glyphicon-th-list" style="margin-right: 20px;margin-top: 10px"></span>我的信息</a></li>
                            <li><a href="{{ url_for('collection.showView') }}"><span class="glyphicon glyphicon-file" style="margin-right: 20px;margin-top: 10px"></span>我的收藏</a></li>
                            <li><a href="{{  url_for('news.todayHotNews')}}"><span class="glyphicon glyphicon-signal" style="margin-right: 20px;margin-top: 10px"></span>今日热点</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="{{ url_for('user.logoutView') }}"><span class="glyphicon glyphicon-off"style="margin-right: 35px"></span>注销</a></li>
                        </ul>
                    </li>
                    {% else %}
                    <li><a href="{{ url_for('news.indexView') }}">请登录</a></li>
                {% endif %}

                {% if is_login %}
                <li><a><img src="{{ avatar }}" style="height: 20px"></a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                       aria-expanded="false">{{ username }}<span class="caret"></span></a>
                    <ul class="dropdown-menu" >
                        <li><a href="{{ url_for('githubuser.get_user') }}">API</a> </li>
                        <li><a href="{{ url_for('githubuser.star') }}" >Repo </a></li>
                        <li><a  href="{{ url_for('githubuser.logout') }}">注销</a></li>
                    </ul>

                {% else %}
                    <li><a href="{{ url_for('githubuser.login') }}"><img src="{{ url_for('static',filename='logo/github.gif') }}" style="height: 20px;"></a></li>
                {% endif %}

            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>


<div class="row clearfix">
    <div class="col-md-12">
        <div >
            <!-- content 预留版块，提供给子模板扩展 -->
            {% block content %}{% endblock %}
        </div>
    </div>
</div>


<!--网站底部-->
<div class="col-md-12">
    <footer class="text-center">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <p>
                        ©&nbsp;2018&nbsp;1000phone.com&nbsp;xICP备 by universe_news
                    </p>
                </div>
            </div>
        </div>
    </footer>
</div>

<!-- js 预留版块，提供给子模板扩展 -->
{% block js %}{% endblock %}
</body>
</html>

apps/templates/error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
测试
</body>
</html>

apps/templates/index_base.html
{% extends 'base.html' %}

{% block content %}
     <div class="col-md-offset-1">
        {#网站内容区#}
        <div class="col-md-2">
            <div>
                <!-- catagory 预留版块，提供给子模板扩展 -->
                {% block catagory %}{% endblock %}
            </div>
        </div>
        <div class="col-md-6">
            <div>
                <div>
                    <!-- 轮播图 预留版块，提供给子模板扩展 -->
                    {% block banner %}{% endblock %}
                </div>
                <div style="margin-top: 20px">
                    <!-- 新闻展示 预留版块，提供给子模板扩展 -->
                    {% block newslist %}{% endblock %}
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div>
                <div>
                    <!-- 用户登录注册,搜索预留版块，提供给子模板扩展 -->
                    {% block user %}

                    {% endblock %}
                </div>
                <div style="margin-top: 20px">
                    <!-- 用户登录注册,搜索预留版块，提供给子模板扩展 -->
                    {% block hot %}{% endblock %}
                </div>
            </div>
        </div>
     </div>

{% endblock %}